/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forms;

import clases.Existencias;
import clases.conexion;
import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author Josue
 */
public class Categoria extends javax.swing.JFrame {

    conexion con = new conexion();
    Connection cn;
    Statement st;
    ResultSet rs;
    DefaultTableModel modelo;
    int id;
    public Categoria() {
        initComponents();
        listar();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btnGuardar = new javax.swing.JButton();
        txtCategoria = new javax.swing.JTextField();
        jSeparator5 = new javax.swing.JSeparator();
        btnEditar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableCategoria = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(34, 33, 74));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Monospaced", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 204, 204));
        jLabel1.setText("INGRESAR CATEGORIAS");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 40, -1, -1));

        jLabel4.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(204, 204, 204));
        jLabel4.setText("Categoria:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 210, -1, -1));

        btnGuardar.setBackground(new java.awt.Color(79, 85, 137));
        btnGuardar.setFont(new java.awt.Font("Monospaced", 1, 16)); // NOI18N
        btnGuardar.setForeground(new java.awt.Color(204, 204, 204));
        btnGuardar.setText("GUARDAR");
        btnGuardar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(169, 80, 161), 3));
        btnGuardar.setContentAreaFilled(false);
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });
        jPanel1.add(btnGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 140, 175, 40));

        txtCategoria.setBackground(new java.awt.Color(34, 33, 74));
        txtCategoria.setFont(new java.awt.Font("Monospaced", 0, 16)); // NOI18N
        txtCategoria.setForeground(new java.awt.Color(204, 204, 204));
        txtCategoria.setBorder(null);
        txtCategoria.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCategoriaKeyTyped(evt);
            }
        });
        jPanel1.add(txtCategoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 200, 140, 30));

        jSeparator5.setForeground(new java.awt.Color(204, 204, 204));
        jPanel1.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 230, 140, -1));

        btnEditar.setBackground(new java.awt.Color(79, 85, 137));
        btnEditar.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        btnEditar.setForeground(new java.awt.Color(204, 204, 204));
        btnEditar.setText("EDITAR");
        btnEditar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(169, 39, 106), 3));
        btnEditar.setContentAreaFilled(false);
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });
        jPanel1.add(btnEditar, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 190, 175, 40));

        tableCategoria.setBackground(new java.awt.Color(45, 55, 99));
        tableCategoria.setForeground(new java.awt.Color(255, 255, 255));
        tableCategoria.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Nombre"
            }
        ));
        tableCategoria.setFocusable(false);
        tableCategoria.setGridColor(new java.awt.Color(153, 153, 153));
        tableCategoria.setIntercellSpacing(new java.awt.Dimension(0, 0));
        tableCategoria.setRowHeight(25);
        tableCategoria.setSelectionBackground(new java.awt.Color(47, 63, 128));
        tableCategoria.setShowVerticalLines(false);
        tableCategoria.getTableHeader().setReorderingAllowed(false);
        tableCategoria.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableCategoriaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tableCategoria);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 370, 880, 130));

        jButton1.setBackground(new java.awt.Color(45, 58, 84));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/cerrar.png"))); // NOI18N
        jButton1.setBorder(null);
        jButton1.setContentAreaFilled(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 10, -1, -1));

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/categoría.png"))); // NOI18N
        jButton2.setBorder(null);
        jButton2.setContentAreaFilled(false);
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 10, 120, 120));

        btnEliminar.setBackground(new java.awt.Color(79, 85, 137));
        btnEliminar.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        btnEliminar.setForeground(new java.awt.Color(204, 204, 204));
        btnEliminar.setText("ELIMINAR");
        btnEliminar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(85, 197, 106), 3));
        btnEliminar.setContentAreaFilled(false);
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });
        jPanel1.add(btnEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 240, 175, 40));

        btnCancelar.setBackground(new java.awt.Color(79, 85, 137));
        btnCancelar.setFont(new java.awt.Font("Monospaced", 1, 16)); // NOI18N
        btnCancelar.setForeground(new java.awt.Color(204, 204, 204));
        btnCancelar.setText("CANCELAR");
        btnCancelar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(169, 80, 161), 3));
        btnCancelar.setContentAreaFilled(false);
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });
        jPanel1.add(btnCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 290, 175, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1080, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1080, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 670, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 670, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        Existencias modSql=new Existencias(); 
        if (txtCategoria.getText().equals("")){
            JOptionPane.showMessageDialog(this, "No dejar el campo de categoria vacio");
            
        }
        else{
        if (modSql.ExistCategori(txtCategoria .getText())==0) {
            agregar();
        this.txtCategoria.setText("");
        listar();
        } else {
            JOptionPane.showMessageDialog(this, "La categoria ya existe");
        }
        }
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void tableCategoriaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableCategoriaMouseClicked
        int fila=tableCategoria.getSelectedRow();
        if(fila==-1){
            JOptionPane.showMessageDialog(null,"Seleccione una Categoria");
        }else{
        id=Integer.parseInt((String)tableCategoria.getValueAt(fila,0).toString());
        String cate=(String)tableCategoria.getValueAt(fila,1);
        txtCategoria.setText(cate);
        }
    }//GEN-LAST:event_tableCategoriaMouseClicked

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        Existencias modSql=new Existencias(); 
        String cat=txtCategoria.getText();
         if (cat.equals("")){
            JOptionPane.showMessageDialog(this, "Debe selecionar en la tabla la categoria a editar");
           
        }
        if (modSql.ExistCategori(txtCategoria.getText())==1) {
             JOptionPane.showMessageDialog(this, "La categoria ya existe!");
        } 
        else {
           
            modificar();  
            listar();
        this.txtCategoria.setText("");
        }
         
    }//GEN-LAST:event_btnEditarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        if (txtCategoria.getText().equals("")){
            JOptionPane.showMessageDialog(this, "Debe selecionar en la tabla la categoria a eliminar");
            
        }
        else{
        eliminar();
        listar();
        nuevo();
        }
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void txtCategoriaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCategoriaKeyTyped
        //Validacion solo letras:
        //Esta funcion se encuentra en los eventos del txtNombre en event con el nombre de KeyTyped
        char validarN = evt.getKeyChar();
        if (Character.isDigit(validarN)) {
            getToolkit().beep();
            evt.consume();
            JOptionPane.showMessageDialog(this, "Por Favor: Ingrese solo letras en la categoria");
        } else if ((int) evt.getKeyChar() >= 33 && (int) evt.getKeyChar() <= 64 ||
                (int) evt.getKeyChar()>=91 && (int) evt.getKeyChar()<=96 ||
                (int) evt.getKeyChar()>=123 && (int) evt.getKeyChar()<=208 ||
                (int) evt.getKeyChar()>=210 && (int) evt.getKeyChar()<=240 ||
                (int) evt.getKeyChar()>=242 && (int) evt.getKeyChar()<=255){
            getToolkit().beep();
            evt.consume();
            JOptionPane.showMessageDialog(this, "No se permiten caracteres especiales");
        }            
    }//GEN-LAST:event_txtCategoriaKeyTyped

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
       nuevo();
    }//GEN-LAST:event_btnCancelarActionPerformed

    void eliminar(){
        int filaseleccionada=tableCategoria.getSelectedRow();
        if(filaseleccionada==-1){
            JOptionPane.showMessageDialog(null,"Seleccione una categoria");
        } else{
            String sql="delete from categoria where id_categoria="+id;
            try{
                cn=con.connx();
                st=cn.createStatement();
                st.executeUpdate(sql);
                JOptionPane.showMessageDialog(null,"Categoria Eliminada");
                limpiartabla();
            }catch (Exception e){
                
            }
        }
    }
    void nuevo(){
        txtCategoria.setText("");
        txtCategoria.requestFocus();
        
    }
    void modificar(){
        String cate=txtCategoria.getText();
        String sql="update categoria set nombre_categoria='"+cate+"' where id_categoria="+id;
        if (cate.equals("")){
            JOptionPane.showMessageDialog(null,"Debe ingresar la Categoria");
            limpiartabla();
        }else{
            try{
                cn=con.connx();
                st=cn.createStatement();
                st.executeUpdate(sql);
                JOptionPane.showMessageDialog(null,"Categoria Actualizada");
                limpiartabla();
            }catch (Exception e){                
            }
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Categoria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Categoria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Categoria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Categoria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Categoria().setVisible(true);
            }
        });
    }
    void listar(){
        String sql="select*from categoria";
        try {
            cn = con.connx();
            st=cn.createStatement();
            rs=st.executeQuery(sql);
            Object[]categoria=new Object[2];
            modelo=(DefaultTableModel)tableCategoria.getModel();
            while(rs.next()){
                categoria[0]=rs.getInt("id_categoria");
                categoria[1]=rs.getString("nombre_categoria");
                modelo.addRow(categoria);
            }
            tableCategoria.setModel(modelo);
        } catch (Exception e) {          
        }                 
    }
    void agregar(){
        String categ = txtCategoria.getText();
        int AutoIncr = 1;
        if(categ.equals("")){
            JOptionPane.showMessageDialog(null,"Ingrese Categoria");
        } else{
            String sql="insert into categoria (nombre_categoria) values('"+categ+"')";
            try {
                cn=con.connx();
                st=cn.createStatement();
                st.executeUpdate(sql);
                limpiartabla();
                JOptionPane.showMessageDialog(null,"Categoria Ingresada");
            } catch (Exception e){
            }
        }
    }
    void limpiartabla(){
        for(int i=0;i<=tableCategoria.getRowCount();i++){
            modelo.removeRow(i);
            i=i-1;
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JTable tableCategoria;
    private javax.swing.JTextField txtCategoria;
    // End of variables declaration//GEN-END:variables
}
