/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package form;

import clases.conexion;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author cerritos
 */
public class Crear_Factura extends javax.swing.JFrame {
conexion conn=new conexion();
    Connection cn;
    Statement st;
    ResultSet rs;
    DefaultTableModel modelo;
    DefaultTableModel modelo2;
    int id;
    /**
     * Creates new form Venta
     */
    public Crear_Factura() {
        initComponents();
        listarFactura();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        txtId = new javax.swing.JTextField();
        btnAnular = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(34, 33, 74));
        jPanel1.setMinimumSize(new java.awt.Dimension(1080, 670));
        jPanel1.setPreferredSize(new java.awt.Dimension(1080, 670));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Monospaced", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 204, 204));
        jLabel1.setText("ANULAR FACTURA");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 30, -1, -1));

        jButton1.setBackground(new java.awt.Color(45, 58, 84));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/cerrar.png"))); // NOI18N
        jButton1.setBorder(null);
        jButton1.setContentAreaFilled(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 10, -1, -1));

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/factura.png"))); // NOI18N
        jButton2.setBorder(null);
        jButton2.setContentAreaFilled(false);
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 10, 120, 120));

        txtId.setBackground(new java.awt.Color(34, 33, 74));
        txtId.setFont(new java.awt.Font("Monospaced", 0, 16)); // NOI18N
        txtId.setForeground(new java.awt.Color(34, 33, 74));
        txtId.setBorder(null);
        txtId.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtIdKeyTyped(evt);
            }
        });
        jPanel1.add(txtId, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 20, 140, 30));

        btnAnular.setBackground(new java.awt.Color(79, 85, 137));
        btnAnular.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        btnAnular.setForeground(new java.awt.Color(204, 204, 204));
        btnAnular.setText("ANULAR");
        btnAnular.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(85, 197, 106), 3));
        btnAnular.setContentAreaFilled(false);
        btnAnular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAnularActionPerformed(evt);
            }
        });
        jPanel1.add(btnAnular, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 590, 175, 40));

        jTable1.setBackground(new java.awt.Color(45, 55, 99));
        jTable1.setForeground(new java.awt.Color(255, 255, 255));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Cliente", "Usuario", "Tipo Venta", "Fecha", "Codigo"
            }
        ));
        jTable1.setFocusable(false);
        jTable1.setGridColor(new java.awt.Color(153, 153, 153));
        jTable1.setIntercellSpacing(new java.awt.Dimension(0, 0));
        jTable1.setRowHeight(25);
        jTable1.setSelectionBackground(new java.awt.Color(47, 63, 128));
        jTable1.setShowVerticalLines(false);
        jTable1.getTableHeader().setReorderingAllowed(false);
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(5).setResizable(false);
        }

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, 1000, 410));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1080, 680));

        pack();
    }// </editor-fold>//GEN-END:initComponents
     public void listarFactura(){
         String sql="select id_factura_venta,nombre,nombre_usuario,nombre_tipo_venta,fecha_venta,codigo from facturaventa \n" +
                      "left join cliente on cliente.id_cliente=facturaventa.id_cliente\n"+
                       "left join usuario on usuario.id_usuario=facturaventa.id_usuario\n"+
                              "left join tipoventa on tipoventa.id_tipo_venta=facturaventa.id_tipo_venta where estado='activa' order by codigo";
    try{
        cn=conn.connx();
        st=cn.createStatement();
        rs=st.executeQuery(sql);
        Object[]proveedor=new Object[6];
        modelo2=(DefaultTableModel)jTable1.getModel();
        while(rs.next()){
        proveedor[0]=rs.getString("id_factura_venta");
        proveedor[1]=rs.getString("nombre");
        proveedor[2]=rs.getString("nombre_usuario");
        proveedor[3]=rs.getString("nombre_tipo_venta");
        proveedor[4]=rs.getString("fecha_venta");
        proveedor[5]=rs.getString("codigo");
        modelo2.addRow(proveedor);
        
        }
        jTable1.setModel(modelo2);
        
    }catch (Exception e){
                    javax.swing.JOptionPane.showMessageDialog(null,"Error"+e.getMessage());
        }
    }public void LimpiarTable(){
         for (int i = 0; i <= jTable1.getRowCount(); i++) {
             modelo2.removeRow(i);
             i=i-1;
         }
     }
     public void Anular(){
        int filaS=jTable1.getSelectedRow();
         if (filaS==-1) {
                 javax.swing.JOptionPane.showMessageDialog(null, "Debe seleccionar una fila para anular");
         }else{
            String sql="update facturaventa set estado='anulada' where id_factura_venta="+id;
             try{
                 cn=conn.connx();
                 st=cn.createStatement();
                 st.executeUpdate(sql);
                 javax.swing.JOptionPane.showMessageDialog(null, "La factura se ha anulado");
                 LimpiarTable();
             }catch(Exception e){}
         }
         
     }
    
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txtIdKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtIdKeyTyped
      
        
    }//GEN-LAST:event_txtIdKeyTyped

    private void btnAnularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAnularActionPerformed

         int  fila=jTable1.getSelectedRow();
         if (fila==-1) {
             javax.swing.JOptionPane.showMessageDialog(null, "Debe selccionar primero una fila en la tabla ");}
         
         else{
             Anular();
              listarFactura();
         }
    }//GEN-LAST:event_btnAnularActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
int  fila=jTable1.getSelectedRow();
            if (fila==-1) {
                          javax.swing.JOptionPane.showMessageDialog(null,"Debe seleccionar una fila para editar");
        }else{
                id= Integer.parseInt((String)jTable1.getValueAt(fila,0).toString());
                
                txtId.setText(""+id);
                
            }    
        
    }//GEN-LAST:event_jTable1MouseClicked

        
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Crear_Factura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Crear_Factura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Crear_Factura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Crear_Factura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Crear_Factura().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAnular;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField txtId;
    // End of variables declaration//GEN-END:variables
}
