/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forms;

import clases.conexion;
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.HashMap;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;
import java.util.logging.Level;
import java.util.logging.Logger;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.util.JRLoader;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author cerritos
 */
public class Generar_Factura extends javax.swing.JFrame {
conexion conn=new conexion();
    Connection cn;
    Statement st;
    ResultSet rs;
    DefaultTableModel modelo;
    DefaultTableModel modelo2;
        DefaultTableModel modelo3;
         DefaultTableModel modelo4;
    Object [] obj= new Object[7];
    int id;
    
    
    /**
     * Creates new form Generar_Factura
     */
    public Generar_Factura() {
        initComponents();
        modelo3=(DefaultTableModel) TablaRegistros.getModel();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        txtIdDetalleVenta = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        txtPrecio = new javax.swing.JTextField();
        jSeparator4 = new javax.swing.JSeparator();
        btnRegistrar = new javax.swing.JButton();
        btnSave = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        txtCant = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator7 = new javax.swing.JSeparator();
        txtProducto = new javax.swing.JTextField();
        jSeparator8 = new javax.swing.JSeparator();
        jSeparator9 = new javax.swing.JSeparator();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtBucarCliente = new javax.swing.JTextField();
        btnCancelar = new javax.swing.JButton();
        jSeparator6 = new javax.swing.JSeparator();
        txtIVA = new javax.swing.JTextField();
        jSeparator10 = new javax.swing.JSeparator();
        jLabel12 = new javax.swing.JLabel();
        txtSub = new javax.swing.JTextField();
        jSeparator12 = new javax.swing.JSeparator();
        jLabel13 = new javax.swing.JLabel();
        jSeparator13 = new javax.swing.JSeparator();
        txtTotal = new javax.swing.JTextField();
        jSeparator14 = new javax.swing.JSeparator();
        jLabel14 = new javax.swing.JLabel();
        txtBucarProducto = new javax.swing.JTextField();
        jSeparator15 = new javax.swing.JSeparator();
        jLabel15 = new javax.swing.JLabel();
        txtCliente = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        btnReporte = new javax.swing.JButton();
        txthaber = new javax.swing.JTextField();
        ver = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        TablaCliente = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        TablaProducto = new javax.swing.JTable();
        ver3 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        TablaFactura = new javax.swing.JTable();
        jScrollPane1 = new javax.swing.JScrollPane();
        TablaRegistros = new javax.swing.JTable();
        jLabel11 = new javax.swing.JLabel();
        txtFecha = new javax.swing.JTextField();
        jSeparator17 = new javax.swing.JSeparator();
        jLabel16 = new javax.swing.JLabel();
        txtDescuento = new javax.swing.JTextField();
        jSeparator18 = new javax.swing.JSeparator();
        verCliente = new javax.swing.JButton();
        verProducto = new javax.swing.JButton();
        txtStockActual = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(34, 33, 74));
        jPanel1.setPreferredSize(new java.awt.Dimension(1080, 670));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Monospaced", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 204, 204));
        jLabel1.setText("GENERAR FACTURA");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 30, -1, -1));

        jButton1.setBackground(new java.awt.Color(45, 58, 84));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/cerrar.png"))); // NOI18N
        jButton1.setBorder(null);
        jButton1.setContentAreaFilled(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 10, -1, -1));

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/factura.png"))); // NOI18N
        jButton2.setBorder(null);
        jButton2.setContentAreaFilled(false);
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, -10, 120, 120));

        txtIdDetalleVenta.setBackground(new java.awt.Color(34, 33, 74));
        txtIdDetalleVenta.setFont(new java.awt.Font("Monospaced", 0, 16)); // NOI18N
        txtIdDetalleVenta.setForeground(new java.awt.Color(34, 33, 74));
        txtIdDetalleVenta.setBorder(null);
        txtIdDetalleVenta.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtIdDetalleVentaKeyTyped(evt);
            }
        });
        jPanel1.add(txtIdDetalleVenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 140, 30));

        jSeparator1.setForeground(new java.awt.Color(204, 204, 204));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 240, 140, -1));

        txtPrecio.setBackground(new java.awt.Color(34, 33, 74));
        txtPrecio.setFont(new java.awt.Font("Monospaced", 0, 16)); // NOI18N
        txtPrecio.setForeground(new java.awt.Color(204, 204, 204));
        txtPrecio.setBorder(null);
        txtPrecio.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtPrecioKeyTyped(evt);
            }
        });
        jPanel1.add(txtPrecio, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 210, 140, 30));

        jSeparator4.setForeground(new java.awt.Color(204, 204, 204));
        jPanel1.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 240, 140, -1));

        btnRegistrar.setBackground(new java.awt.Color(79, 85, 137));
        btnRegistrar.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        btnRegistrar.setForeground(new java.awt.Color(204, 204, 204));
        btnRegistrar.setText("REGISTRAR");
        btnRegistrar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(169, 80, 161), 3));
        btnRegistrar.setContentAreaFilled(false);
        btnRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarActionPerformed(evt);
            }
        });
        jPanel1.add(btnRegistrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 400, 130, 40));

        btnSave.setBackground(new java.awt.Color(79, 85, 137));
        btnSave.setFont(new java.awt.Font("Monospaced", 1, 16)); // NOI18N
        btnSave.setForeground(new java.awt.Color(204, 204, 204));
        btnSave.setText("GUARDAR");
        btnSave.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(85, 197, 106), 3));
        btnSave.setContentAreaFilled(false);
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });
        jPanel1.add(btnSave, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 400, 120, 40));

        jLabel7.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(204, 204, 204));
        jLabel7.setText("Poducto:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 170, -1, -1));

        txtCant.setBackground(new java.awt.Color(34, 33, 74));
        txtCant.setFont(new java.awt.Font("Monospaced", 0, 16)); // NOI18N
        txtCant.setForeground(new java.awt.Color(204, 204, 204));
        txtCant.setBorder(null);
        txtCant.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCantKeyTyped(evt);
            }
        });
        jPanel1.add(txtCant, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 260, 140, 30));

        jSeparator2.setForeground(new java.awt.Color(204, 204, 204));
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 190, 140, -1));

        jSeparator7.setForeground(new java.awt.Color(204, 204, 204));
        jPanel1.add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 190, 140, -1));

        txtProducto.setBackground(new java.awt.Color(34, 33, 74));
        txtProducto.setFont(new java.awt.Font("Monospaced", 0, 16)); // NOI18N
        txtProducto.setForeground(new java.awt.Color(204, 204, 204));
        txtProducto.setBorder(null);
        txtProducto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtProductoKeyTyped(evt);
            }
        });
        jPanel1.add(txtProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 160, 140, 30));

        jSeparator8.setForeground(new java.awt.Color(204, 204, 204));
        jPanel1.add(jSeparator8, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 190, 140, -1));

        jSeparator9.setForeground(new java.awt.Color(204, 204, 204));
        jPanel1.add(jSeparator9, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 290, 140, 20));

        jLabel8.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(204, 204, 204));
        jLabel8.setText("Cantidad:");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 270, -1, 20));

        jLabel9.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(204, 204, 204));
        jLabel9.setText("Cliente:");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, -1, -1));

        txtBucarCliente.setBackground(new java.awt.Color(34, 33, 74));
        txtBucarCliente.setFont(new java.awt.Font("Monospaced", 0, 16)); // NOI18N
        txtBucarCliente.setForeground(new java.awt.Color(204, 204, 204));
        txtBucarCliente.setBorder(null);
        txtBucarCliente.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtBucarClienteKeyTyped(evt);
            }
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtBucarClienteKeyPressed(evt);
            }
        });
        jPanel1.add(txtBucarCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 150, 140, 30));

        btnCancelar.setBackground(new java.awt.Color(79, 85, 137));
        btnCancelar.setFont(new java.awt.Font("Monospaced", 1, 16)); // NOI18N
        btnCancelar.setForeground(new java.awt.Color(204, 204, 204));
        btnCancelar.setText("CANCELAR");
        btnCancelar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(169, 80, 161), 3));
        btnCancelar.setContentAreaFilled(false);
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });
        jPanel1.add(btnCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 400, 120, 40));

        jSeparator6.setForeground(new java.awt.Color(204, 204, 204));
        jPanel1.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 550, 140, -1));

        txtIVA.setBackground(new java.awt.Color(34, 33, 74));
        txtIVA.setFont(new java.awt.Font("Monospaced", 0, 16)); // NOI18N
        txtIVA.setForeground(new java.awt.Color(204, 204, 204));
        txtIVA.setBorder(null);
        txtIVA.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtIVAKeyTyped(evt);
            }
        });
        jPanel1.add(txtIVA, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 520, 140, 30));

        jSeparator10.setForeground(new java.awt.Color(204, 204, 204));
        jPanel1.add(jSeparator10, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 550, 140, -1));

        jLabel12.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(204, 204, 204));
        jLabel12.setText("IVA:");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 530, -1, -1));

        txtSub.setBackground(new java.awt.Color(34, 33, 74));
        txtSub.setFont(new java.awt.Font("Monospaced", 0, 16)); // NOI18N
        txtSub.setForeground(new java.awt.Color(204, 204, 204));
        txtSub.setBorder(null);
        txtSub.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtSubKeyTyped(evt);
            }
        });
        jPanel1.add(txtSub, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 460, 140, 30));

        jSeparator12.setForeground(new java.awt.Color(204, 204, 204));
        jPanel1.add(jSeparator12, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 490, 140, 20));

        jLabel13.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(204, 204, 204));
        jLabel13.setText("SubTotal:");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 470, -1, 20));

        jSeparator13.setForeground(new java.awt.Color(204, 204, 204));
        jPanel1.add(jSeparator13, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 600, 140, -1));

        txtTotal.setEditable(false);
        txtTotal.setBackground(new java.awt.Color(34, 33, 74));
        txtTotal.setFont(new java.awt.Font("Monospaced", 0, 16)); // NOI18N
        txtTotal.setForeground(new java.awt.Color(204, 204, 204));
        txtTotal.setBorder(null);
        txtTotal.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtTotalKeyTyped(evt);
            }
        });
        jPanel1.add(txtTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 570, 140, 30));

        jSeparator14.setForeground(new java.awt.Color(204, 204, 204));
        jPanel1.add(jSeparator14, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 600, 140, -1));

        jLabel14.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(204, 204, 204));
        jLabel14.setText("Total:");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 580, -1, -1));

        txtBucarProducto.setBackground(new java.awt.Color(34, 33, 74));
        txtBucarProducto.setFont(new java.awt.Font("Monospaced", 0, 16)); // NOI18N
        txtBucarProducto.setForeground(new java.awt.Color(204, 204, 204));
        txtBucarProducto.setBorder(null);
        txtBucarProducto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtBucarProductoKeyTyped(evt);
            }
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtBucarProductoKeyPressed(evt);
            }
        });
        jPanel1.add(txtBucarProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 150, 140, 30));

        jSeparator15.setForeground(new java.awt.Color(204, 204, 204));
        jPanel1.add(jSeparator15, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 180, 140, 20));

        jLabel15.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(204, 204, 204));
        jLabel15.setText("Buscar");
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 160, -1, 20));

        txtCliente.setBackground(new java.awt.Color(34, 33, 74));
        txtCliente.setFont(new java.awt.Font("Monospaced", 0, 16)); // NOI18N
        txtCliente.setForeground(new java.awt.Color(204, 204, 204));
        txtCliente.setBorder(null);
        txtCliente.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtClienteKeyTyped(evt);
            }
        });
        jPanel1.add(txtCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 160, 140, 30));

        jLabel10.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(204, 204, 204));
        jLabel10.setText("Precio:");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 220, -1, -1));

        btnReporte.setBackground(new java.awt.Color(79, 85, 137));
        btnReporte.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        btnReporte.setForeground(new java.awt.Color(204, 204, 204));
        btnReporte.setText("IMPRIMIR");
        btnReporte.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(169, 39, 106), 3));
        btnReporte.setContentAreaFilled(false);
        btnReporte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReporteActionPerformed(evt);
            }
        });
        jPanel1.add(btnReporte, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 400, 130, 40));

        txthaber.setBackground(new java.awt.Color(34, 33, 74));
        txthaber.setFont(new java.awt.Font("Monospaced", 0, 16)); // NOI18N
        txthaber.setForeground(new java.awt.Color(34, 33, 74));
        txthaber.setBorder(null);
        txthaber.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txthaberKeyTyped(evt);
            }
        });
        jPanel1.add(txthaber, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 0, 140, 30));

        ver.setBackground(new java.awt.Color(34, 33, 74));
        ver.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        TablaCliente.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        TablaCliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TablaClienteMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(TablaCliente);

        ver.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(-5, -2, 420, 200));

        jPanel1.add(ver, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 190, 430, 210));

        TablaProducto.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        TablaProducto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TablaProductoMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(TablaProducto);

        jPanel1.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 190, 410, 210));

        ver3.setBackground(new java.awt.Color(34, 33, 74));
        ver3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        TablaFactura.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        TablaFactura.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TablaFacturaMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(TablaFactura);

        ver3.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 650, 150));

        jPanel1.add(ver3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 480, 650, 150));

        TablaRegistros.setBackground(new java.awt.Color(45, 55, 99));
        TablaRegistros.setForeground(new java.awt.Color(255, 255, 255));
        TablaRegistros.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Producto", "Cantidad", "Precio", "Descuento", "Monto", "Stock", "Nuevo Stock"
            }
        ));
        TablaRegistros.setFocusable(false);
        TablaRegistros.setGridColor(new java.awt.Color(153, 153, 153));
        TablaRegistros.setIntercellSpacing(new java.awt.Dimension(0, 0));
        TablaRegistros.setRowHeight(25);
        TablaRegistros.setSelectionBackground(new java.awt.Color(47, 63, 128));
        TablaRegistros.setShowVerticalLines(false);
        TablaRegistros.getTableHeader().setReorderingAllowed(false);
        TablaRegistros.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TablaRegistrosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(TablaRegistros);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 480, 640, 120));

        jLabel11.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(204, 204, 204));
        jLabel11.setText("Fecha:");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, -1, -1));

        txtFecha.setBackground(new java.awt.Color(34, 33, 74));
        txtFecha.setFont(new java.awt.Font("Monospaced", 0, 16)); // NOI18N
        txtFecha.setForeground(new java.awt.Color(204, 204, 204));
        txtFecha.setText("09/05/20");
        txtFecha.setBorder(null);
        txtFecha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFechaActionPerformed(evt);
            }
        });
        txtFecha.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtFechaKeyTyped(evt);
            }
        });
        jPanel1.add(txtFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 220, 140, 30));

        jSeparator17.setForeground(new java.awt.Color(204, 204, 204));
        jPanel1.add(jSeparator17, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 250, 140, 20));

        jLabel16.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(204, 204, 204));
        jLabel16.setText("Descuento:");
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 320, -1, -1));

        txtDescuento.setBackground(new java.awt.Color(34, 33, 74));
        txtDescuento.setFont(new java.awt.Font("Monospaced", 0, 16)); // NOI18N
        txtDescuento.setForeground(new java.awt.Color(204, 204, 204));
        txtDescuento.setBorder(null);
        txtDescuento.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtDescuentoKeyTyped(evt);
            }
        });
        jPanel1.add(txtDescuento, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 310, 140, 30));

        jSeparator18.setForeground(new java.awt.Color(204, 204, 204));
        jPanel1.add(jSeparator18, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 340, 140, 20));

        verCliente.setBackground(new java.awt.Color(79, 85, 137));
        verCliente.setFont(new java.awt.Font("Monospaced", 0, 12)); // NOI18N
        verCliente.setForeground(new java.awt.Color(204, 204, 204));
        verCliente.setText("VER");
        verCliente.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(169, 80, 161), 3));
        verCliente.setContentAreaFilled(false);
        verCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                verClienteActionPerformed(evt);
            }
        });
        jPanel1.add(verCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 160, 50, 30));

        verProducto.setBackground(new java.awt.Color(79, 85, 137));
        verProducto.setFont(new java.awt.Font("Monospaced", 0, 12)); // NOI18N
        verProducto.setForeground(new java.awt.Color(204, 204, 204));
        verProducto.setText("VER");
        verProducto.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(169, 80, 161), 3));
        verProducto.setContentAreaFilled(false);
        verProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                verProductoActionPerformed(evt);
            }
        });
        jPanel1.add(verProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 160, 50, 30));

        txtStockActual.setBackground(new java.awt.Color(34, 33, 74));
        txtStockActual.setFont(new java.awt.Font("Monospaced", 0, 16)); // NOI18N
        txtStockActual.setForeground(new java.awt.Color(34, 33, 74));
        txtStockActual.setBorder(null);
        txtStockActual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtStockActualActionPerformed(evt);
            }
        });
        txtStockActual.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtStockActualKeyTyped(evt);
            }
        });
        jPanel1.add(txtStockActual, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 0, 140, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txtIdDetalleVentaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtIdDetalleVentaKeyTyped

    }//GEN-LAST:event_txtIdDetalleVentaKeyTyped

    private void txtPrecioKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPrecioKeyTyped

    }//GEN-LAST:event_txtPrecioKeyTyped

    private void btnRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarActionPerformed
        if (txtCliente.getText().equals("")||txtProducto.getText().equals("")||txtCant.getText().equals("")||txtPrecio.getText().equals("")||txtCliente.getText().equals("")) {
            javax.swing.JOptionPane.showMessageDialog(this, "No debe haber campos vacios");
        }
        else{
            TablaRegistros.setVisible(true);
            ver3.setVisible(false);
            obj[0]=txtProducto.getText();
            obj[1]=txtCant.getText();
            obj[2]=txtPrecio.getText();
            obj[3]=txtDescuento.getText();
            obj[5]=txtStockActual.getText();

            modelo3.addRow(obj);}
        if (txtCliente.getText().equals("")||txtProducto.getText().equals("")||txtCant.getText().equals("")||txtPrecio.getText().equals("")||txtCliente.getText().equals("")) {
            javax.swing.JOptionPane.showMessageDialog(this, "No debe haber campos vacios");
        }
        else{
            String pre;
            String can,sa,sn = null;
            double iva=0;
            double total=0;
            double subtotal=0;
            double precio;
            int cantidad,saN,sNN;
            double imp=0.0;

            for(int i=0;i<TablaRegistros.getRowCount();i++)
            {
                can=TablaRegistros.getValueAt(i, 1).toString();
                pre=TablaRegistros.getValueAt(i, 2).toString();
                String des=txtDescuento.getText();
            double desc=Double.parseDouble(des);
                precio=Double.parseDouble(pre);
                cantidad=Integer.parseInt(can);
                imp=(precio-desc)*cantidad;
                subtotal=subtotal+imp;
                iva=subtotal*0.13;
                total=subtotal+iva;
                TablaRegistros.setValueAt(Math.rint(imp*100)/100, i, 4);
//                sa=TablaFactura.getValueAt(i, 4).toString();
                   String ca=txtCant.getText();
            int cann=Integer.parseInt(ca);
            sa=txtStockActual.getText();
         
                saN=Integer.parseInt(sa);
                int valor=saN-cann;
                txthaber.setText(""+valor);
                sa=TablaRegistros.getValueAt(i, 5).toString();
            saN=Integer.parseInt(sa);
            TablaRegistros.setValueAt((saN-cantidad), i, 6);

            }
            
            txtSub.setText(Double.toString(subtotal));
            txtIVA.setText(""+Math.rint(iva*100)/100);
            txtTotal.setText(""+Math.rint(total*100)/100);
         
                

        }
    }//GEN-LAST:event_btnRegistrarActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        if (txtSub.getText().equals("")||txtTotal.getText().equals("")||txtIVA.getText().equals("")||txtDescuento.getText().equals("")) {
            javax.swing.JOptionPane.showMessageDialog(this, "No debe haber campos vacios");
        }
        else{
            AgregarF();
            Rfactura();
//            SumarCant();
            //        txtFactura.setText("");
            txtProducto.setText("");
            txtCliente.setText("");
            txtPrecio.setText("");
            txtCant.setText("");
            txtTotal.setText("");
            txtIVA.setText("");
            txtSub.setText("");
            String nombrecolumnas[]={"Id","Fecha","Cliente","Total"};
        String data[][]=new String [0][0];
        ver3.setVisible(true);
        TablaFactura.setModel(new DefaultTableModel(data,nombrecolumnas));

        //        TablaMuestras.getTableHeader().setVisible(false);
        listarDetalle();
        }
    }//GEN-LAST:event_btnSaveActionPerformed

    private void txtCantKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCantKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCantKeyTyped

    private void txtProductoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtProductoKeyTyped
        if (txtProducto.getText().length() >= 1) {
            evt.consume();
            Toolkit.getDefaultToolkit().beep();
        }
        //Validar que solo se puedan escribir numeros
        char validarN = evt.getKeyChar();
        if (Character.isLetter(validarN)) {
            getToolkit().beep();
            evt.consume();
            javax.swing.JOptionPane.showMessageDialog(this, "Por Favor: Ingrese solo numeros en el Producto");
        } else if ((int) evt.getKeyChar() >= 32 && (int) evt.getKeyChar() <= 47  ||
            (int) evt.getKeyChar()>=58 && (int) evt.getKeyChar()<=255){
            getToolkit().beep();
            evt.consume();
            javax.swing.JOptionPane.showMessageDialog(this, "Por Favor: Ingrese solo numeros en el Producto");
        }
    }//GEN-LAST:event_txtProductoKeyTyped

    private void txtBucarClienteKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBucarClienteKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBucarClienteKeyTyped

    private void txtBucarClienteKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBucarClienteKeyPressed
        String[] titulos = {"Id","Codigo","Fecha"};
        String[] registros = new String[50];

        String sql = "select id_cliente,nombre,apellido from cliente WHERE nombre LIKE '%" + txtBucarCliente.getText() + "%'";
        modelo = new DefaultTableModel(null, titulos);
        conexion cc = new conexion();
        Connection conect = cc.connx();
        try {
            Statement st = (Statement) conect.createStatement();
            ResultSet rs = st.executeQuery(sql);
            while (rs.next()) {
                registros[0] = rs.getString("id_cliente");
                registros[1] = rs.getString("nombre");
                registros[2] = rs.getString("apellido");
                modelo.addRow(registros);

            }
            TablaCliente.setModel(modelo);

        } catch (SQLException ex) {
            javax.swing.JOptionPane.showMessageDialog(null, ex);
        }
    }//GEN-LAST:event_txtBucarClienteKeyPressed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        cancelar();

    }//GEN-LAST:event_btnCancelarActionPerformed

    private void txtIVAKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtIVAKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIVAKeyTyped

    private void txtSubKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSubKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSubKeyTyped

    private void txtTotalKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTotalKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTotalKeyTyped

    private void txtBucarProductoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBucarProductoKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBucarProductoKeyTyped

    private void txtBucarProductoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBucarProductoKeyPressed
        String[] titulos = {"Id","Producto","Marca","Stock"};
        String[] registros = new String[50];

        String sql = "select id_producto,nombre_producto,nombre_marca,stock from producto\n" +
        "inner join marca on marca.id_marca=producto.id_marca WHERE nombre_producto LIKE '%" + txtBucarProducto.getText() + "%'";
        modelo = new DefaultTableModel(null, titulos);
        conexion cc = new conexion();
        Connection conect = cc.connx();
        try {
            Statement st = (Statement) conect.createStatement();
            ResultSet rs = st.executeQuery(sql);
            while (rs.next()) {
                registros[0]=rs.getString("id_producto");
                registros[1]=rs.getString("nombre_producto");
                registros[2]=rs.getString("nombre_marca");
                registros[3]=rs.getString("stock");

                modelo.addRow(registros);
            }
            TablaProducto.setModel(modelo);

        } catch (SQLException ex) {
            javax.swing.JOptionPane.showMessageDialog(null, ex);
        }
    }//GEN-LAST:event_txtBucarProductoKeyPressed

    private void txtClienteKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtClienteKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtClienteKeyTyped

    private void btnReporteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReporteActionPerformed
        this.factura();
    }//GEN-LAST:event_btnReporteActionPerformed

    private void txthaberKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txthaberKeyTyped
        // Validar que solo escriba letras
        //Esta funcion se encuentra en los eventos del txtNombre en event con el nombre de KeyTyped
        char validarN = evt.getKeyChar();
        if (Character.isDigit(validarN)) {
            getToolkit().beep();
            evt.consume();
            JOptionPane.showMessageDialog(this, "Por Favor: Ingrese solo letras en el Nombre");
        } else if ((int) evt.getKeyChar() >= 33 && (int) evt.getKeyChar() <= 64 ||
            (int) evt.getKeyChar()>=91 && (int) evt.getKeyChar()<=96 ||
            (int) evt.getKeyChar()>=123 && (int) evt.getKeyChar()<=208 ||
            (int) evt.getKeyChar()>=210 && (int) evt.getKeyChar()<=240 ||
            (int) evt.getKeyChar()>=242 && (int) evt.getKeyChar()<=255){
            getToolkit().beep();
            evt.consume();
            JOptionPane.showMessageDialog(this, "No se permiten caracteres especiales");
        }
    }//GEN-LAST:event_txthaberKeyTyped

    private void TablaClienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TablaClienteMouseClicked
        int  fila=TablaCliente.getSelectedRow();
        if (fila==-1) {
            javax.swing.JOptionPane.showMessageDialog(null,"Debe seleccionar una fila para agregar");
        }else{
            id= Integer.parseInt((String)TablaCliente.getValueAt(fila,0).toString());
            txtCliente.setText(""+id);
        }
    }//GEN-LAST:event_TablaClienteMouseClicked

    private void TablaProductoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TablaProductoMouseClicked
      int  fila=TablaProducto.getSelectedRow();
        if (fila==-1) {
            javax.swing.JOptionPane.showMessageDialog(null,"Debe seleccionar una fila para agregar");
        }else{
            id= Integer.parseInt((String)TablaProducto.getValueAt(fila,0).toString());
            String stock=(String)TablaProducto.getValueAt(fila,3);
            String pre=(String)TablaProducto.getValueAt(fila,4);
            txtProducto.setText(""+id);
            txtStockActual.setText(stock);
            txtPrecio.setText(pre);
        } 
    }//GEN-LAST:event_TablaProductoMouseClicked

    private void TablaRegistrosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TablaRegistrosMouseClicked

    }//GEN-LAST:event_TablaRegistrosMouseClicked

    private void txtFechaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFechaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFechaActionPerformed

    private void txtFechaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtFechaKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFechaKeyTyped

    private void txtDescuentoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDescuentoKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDescuentoKeyTyped

    private void verClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_verClienteActionPerformed
        this.txtBucarProducto.setVisible(false);
        this.txtBucarCliente.setVisible(true);
        String nombrecolumnas[]={"Id","Nombre","Apellido"};
        String data[][]=new String [0][0];
        ver.setVisible(true);

        TablaCliente.setModel(new DefaultTableModel(data,nombrecolumnas));

        //        TablaMuestras.getTableHeader().setVisible(false);
        ListarCliente();
        //        TablaMuestras.getColumnModel().getColumn(0).setMaxWidth(0);
        //        TablaMuestras.getColumnModel().getColumn(0).setMinWidth(0);
        //        TablaMuestras.getColumnModel().getColumn(0).setPreferredWidth(0);

        //        TablaMuestras.getTableHeader().setVisible(false);
    }//GEN-LAST:event_verClienteActionPerformed

    private void verProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_verProductoActionPerformed
        this.txtBucarProducto.setVisible(true);
        this.txtBucarCliente.setVisible(false);
        String nombrecolumnas[]={"Id","Producto","Marca","Stock","Precio"};
        String data[][]=new String [0][0];
        ver.setVisible(false);
        
        TablaProducto.setModel(new DefaultTableModel(data,nombrecolumnas));
              
        
//        TablaMuestras.getTableHeader().setVisible(false);
    ListarProducto();
    }//GEN-LAST:event_verProductoActionPerformed

    private void txtStockActualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtStockActualActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtStockActualActionPerformed

    private void txtStockActualKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtStockActualKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtStockActualKeyTyped

    private void TablaFacturaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TablaFacturaMouseClicked
         int  fila=TablaFactura.getSelectedRow();
        if (fila==-1) {
            javax.swing.JOptionPane.showMessageDialog(null,"Debe seleccionar una fila para agregar");
        }else{
            id= Integer.parseInt((String)TablaFactura.getValueAt(fila,0).toString());
            txtIdDetalleVenta.setText(""+id);
        }
        
    }//GEN-LAST:event_TablaFacturaMouseClicked
       public void ListarProducto(){
         String sql="select id_producto,nombre_producto,nombre_marca,stock,precio_venta from producto\n" +
                        "inner join marca on marca.id_marca=producto.id_marca";
    try{
        cn=conn.connx();
        st=cn.createStatement();
        rs=st.executeQuery(sql);
        Object[]proveedor=new Object[5];
        modelo=(DefaultTableModel)TablaProducto.getModel();
        while(rs.next()){
        proveedor[0]=rs.getInt("id_producto");
        proveedor[1]=rs.getString("nombre_producto");
        proveedor[2]=rs.getString("nombre_marca");
        proveedor[3]=rs.getString("stock");
        proveedor[4]=rs.getString("precio_venta");
        modelo.addRow(proveedor);
        
        }
        TablaProducto.setModel(modelo);
        
    }catch (Exception e){
                    javax.swing.JOptionPane.showMessageDialog(null,"Error"+e.getMessage());
        }
    }
       public void ListarCliente(){
         String sql="select id_cliente,nombre,apellido from cliente";
    try{
        cn=conn.connx();
        st=cn.createStatement();
        rs=st.executeQuery(sql);
        Object[]proveedor=new Object[3];
        modelo2=(DefaultTableModel)TablaCliente.getModel();
        while(rs.next()){
        proveedor[0]=rs.getInt("id_cliente");
        proveedor[1]=rs.getString("nombre");
        proveedor[2]=rs.getString("apellido");
        modelo2.addRow(proveedor);
        
        }
        TablaCliente.setModel(modelo2);
        
    }catch (Exception e){
                    javax.swing.JOptionPane.showMessageDialog(null,"Error"+e.getMessage());
        }
       }

           public void SumarCant(){
               int fila=0;
               int total=0;
               String stockact=null;
               stockact=txtStockActual.getText();
               
             for (int i = 0; i < TablaRegistros.getRowCount(); i++) {
                   String stock=TablaRegistros.getValueAt(i, 5).toString();
                   String ide=TablaRegistros.getValueAt(i, 1).toString();
               String sql="update producto set stock='"+stock+"' where id_producto="+ide;
         if (stockact.equals("")) {
             javax.swing.JOptionPane.showMessageDialog(null, "No deben haber campos vacios");
         }else{
             try{
                 cn=conn.connx();
                 st=cn.createStatement();
                 st.executeUpdate(sql);

                 javax.swing.JOptionPane.showMessageDialog(null, "El stock ha sido actualizado");                
             }catch(Exception e){}
         }
                }
               txtStockActual.setText(""+total);
           
           }
           public void AgregarF(){
     String fecha=txtFecha.getText();
     String cli=txtCliente.getText();
     
         if (cli.equals("")||fecha.equals("")) {
             javax.swing.JOptionPane.showMessageDialog(null,"Debe ingresar los campos que estan vacios");
         }else {
                String sql="insert into facturaventa (id_cliente,id_usuario,id_tipo_venta,fecha_venta,estado) values ('"+cli+"','1','1','"+fecha+"','activa')";
                try{
                        cn=conn.connx();
                        st=cn.createStatement();
                        st.executeUpdate(sql);
                }catch(Exception e){
                 //JOptionPane.showMessageDialog(null,"Error"+e.getMessage());
                }
         }
     }
           
           public void Rfactura(){
               for(int i=0;i<TablaRegistros.getRowCount();i++)
        {
        String idprod=TablaRegistros.getValueAt(i, 0).toString();
        String cant=TablaRegistros.getValueAt(i, 1).toString();
        String preunit=TablaRegistros.getValueAt(i, 2).toString();
        String desc=TablaRegistros.getValueAt(i, 3).toString();
        String monto=TablaRegistros.getValueAt(i, 4).toString();
        String total=txtTotal.getText();
        if (total.equals("")) {
             javax.swing.JOptionPane.showMessageDialog(null,"Debe ingresar los campos que estan vacios");
         }else {
        String sql="insert into detalleventa (id_producto,cantidad,precio,monto,descuento,total) VALUES ('"+idprod+"','"+cant+"','"+preunit+"','"+monto+"','"+desc+"','"+total+"')";
        
        try {          
                         cn=conn.connx();
                        st=cn.createStatement();
                        st.executeUpdate(sql);
                       
        } catch (SQLException ex) {
                        javax.swing.JOptionPane.showMessageDialog(null, "No se pudo registrarrrrrr");
            }
        }
    }
        }
           
           public void listarDetalle(){
         String sql=" select facturaventa.id_factura_venta,fecha_venta,nombre,total from facturaventa\n" +
                    "inner join cliente on facturaventa.id_cliente=cliente.id_cliente\n" +
                    "inner join detalleventa on facturaventa.id_factura_venta=detalleventa.id_factura_venta";
    try{
        cn=conn.connx();
        st=cn.createStatement();
        rs=st.executeQuery(sql);
        Object[]proveedor=new Object[4];
        modelo4=(DefaultTableModel)TablaFactura.getModel();
        while(rs.next()){
        proveedor[0]=rs.getInt("id_factura_venta");
        proveedor[1]=rs.getString("fecha_venta");
        proveedor[2]=rs.getString("nombre");
        proveedor[3]=rs.getString("total");
        modelo4.addRow(proveedor);
        
        }
        TablaFactura.setModel(modelo4);
        
    }catch (Exception e){
                    javax.swing.JOptionPane.showMessageDialog(null,"Error"+e.getMessage());
        }
    }
           
           public void factura(){
        try {
        JasperReport reporte = null;
        String path = "src/Reportes/factura.jasper";
        String idfac = txtIdDetalleVenta.getText();
        
        Map parametro = new HashMap();
        parametro.put("Factura", idfac);
        
            reporte = (JasperReport) JRLoader.loadObjectFromFile(path);
            JasperPrint jprint = JasperFillManager.fillReport(reporte, parametro, cn);
            JasperViewer view = new JasperViewer(jprint, false);
            view.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
            view.setVisible(true);
        } catch (JRException ex) {
            Logger.getLogger(Generar_Factura.class.getName()).log(Level.SEVERE, null, ex);
        }
           }
           
           
     
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Generar_Factura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Generar_Factura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Generar_Factura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Generar_Factura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Generar_Factura().setVisible(true);
            }
        });
    }
    public void cancelar(){
        txtProducto.setText("");
        txtCliente.setText("");
        txtCant.setText("");
        txtPrecio.setText("");
        txtDescuento.setText("");
        txtFecha.setText("");
        txtSub.setText("");
        txtIVA.setText("");
        txtTotal.setText("");
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable TablaCliente;
    private javax.swing.JTable TablaFactura;
    private javax.swing.JTable TablaProducto;
    private javax.swing.JTable TablaRegistros;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnRegistrar;
    private javax.swing.JButton btnReporte;
    private javax.swing.JButton btnSave;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator10;
    private javax.swing.JSeparator jSeparator12;
    private javax.swing.JSeparator jSeparator13;
    private javax.swing.JSeparator jSeparator14;
    private javax.swing.JSeparator jSeparator15;
    private javax.swing.JSeparator jSeparator17;
    private javax.swing.JSeparator jSeparator18;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JSeparator jSeparator9;
    private javax.swing.JTextField txtBucarCliente;
    private javax.swing.JTextField txtBucarProducto;
    private javax.swing.JTextField txtCant;
    private javax.swing.JTextField txtCliente;
    private javax.swing.JTextField txtDescuento;
    private javax.swing.JTextField txtFecha;
    private javax.swing.JTextField txtIVA;
    private javax.swing.JTextField txtIdDetalleVenta;
    private javax.swing.JTextField txtPrecio;
    private javax.swing.JTextField txtProducto;
    private javax.swing.JTextField txtStockActual;
    private javax.swing.JTextField txtSub;
    private javax.swing.JTextField txtTotal;
    private javax.swing.JTextField txthaber;
    private javax.swing.JPanel ver;
    private javax.swing.JPanel ver3;
    private javax.swing.JButton verCliente;
    private javax.swing.JButton verProducto;
    // End of variables declaration//GEN-END:variables
}
