/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forms;

import clases.conexion;
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.HashMap;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;
import java.util.logging.Level;
import java.util.logging.Logger;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.util.JRLoader;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author cerritos
 */
public class Generar_Factura1 extends javax.swing.JFrame {
conexion conn=new conexion();
    Connection cn;
    Statement st;
    ResultSet rs;
    DefaultTableModel modelo;
    DefaultTableModel modelo2;
    DefaultTableModel modelo3;
    Object [] obj= new Object[7];
    int id;
    
    
    /**
     * Creates new form Generar_Factura
     */
    public Generar_Factura1() {
        initComponents();
        modelo3=(DefaultTableModel) TablaFacturas.getModel();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        txtIdDetalleVenta = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        txtPrecio = new javax.swing.JTextField();
        jSeparator4 = new javax.swing.JSeparator();
        jLabel6 = new javax.swing.JLabel();
        btnRegistrar = new javax.swing.JButton();
        btnSave = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        txtCant = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        txtFactura = new javax.swing.JTextField();
        jSeparator7 = new javax.swing.JSeparator();
        txtProducto = new javax.swing.JTextField();
        jSeparator8 = new javax.swing.JSeparator();
        jSeparator9 = new javax.swing.JSeparator();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        verProducto = new javax.swing.JButton();
        verFactura = new javax.swing.JButton();
        aggProducto = new javax.swing.JButton();
        aggFactura = new javax.swing.JButton();
        txtBucarFac = new javax.swing.JTextField();
        btnCancelar = new javax.swing.JButton();
        jSeparator6 = new javax.swing.JSeparator();
        txtIVA = new javax.swing.JTextField();
        jSeparator10 = new javax.swing.JSeparator();
        jLabel12 = new javax.swing.JLabel();
        txtSub = new javax.swing.JTextField();
        jSeparator12 = new javax.swing.JSeparator();
        jLabel13 = new javax.swing.JLabel();
        jSeparator13 = new javax.swing.JSeparator();
        txtTotal = new javax.swing.JTextField();
        jSeparator14 = new javax.swing.JSeparator();
        jLabel14 = new javax.swing.JLabel();
        txtBucarProducto = new javax.swing.JTextField();
        jSeparator15 = new javax.swing.JSeparator();
        jLabel15 = new javax.swing.JLabel();
        txtStockActual = new javax.swing.JTextField();
        jSeparator16 = new javax.swing.JSeparator();
        jLabel10 = new javax.swing.JLabel();
        btnReporte = new javax.swing.JButton();
        ver = new javax.swing.JPanel();
        ver1 = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        TablaCliente1 = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        TablaCliente = new javax.swing.JTable();
        ver3 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        TablaProducto = new javax.swing.JTable();
        jScrollPane1 = new javax.swing.JScrollPane();
        TablaFacturas = new javax.swing.JTable();
        verr = new javax.swing.JButton();
        ver2 = new javax.swing.JPanel();
        jScrollPane6 = new javax.swing.JScrollPane();
        TablaCliente2 = new javax.swing.JTable();
        ver4 = new javax.swing.JPanel();
        jScrollPane7 = new javax.swing.JScrollPane();
        TablaCliente3 = new javax.swing.JTable();
        jScrollPane4 = new javax.swing.JScrollPane();
        TablaIngresos = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(34, 33, 74));
        jPanel1.setPreferredSize(new java.awt.Dimension(1080, 670));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Monospaced", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 204, 204));
        jLabel1.setText("GENERAR FACTURA");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 30, -1, -1));

        jButton1.setBackground(new java.awt.Color(45, 58, 84));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/cerrar.png"))); // NOI18N
        jButton1.setBorder(null);
        jButton1.setContentAreaFilled(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 10, -1, -1));

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/factura.png"))); // NOI18N
        jButton2.setBorder(null);
        jButton2.setContentAreaFilled(false);
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 10, 120, 120));

        txtIdDetalleVenta.setBackground(new java.awt.Color(34, 33, 74));
        txtIdDetalleVenta.setFont(new java.awt.Font("Monospaced", 0, 16)); // NOI18N
        txtIdDetalleVenta.setForeground(new java.awt.Color(34, 33, 74));
        txtIdDetalleVenta.setBorder(null);
        txtIdDetalleVenta.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtIdDetalleVentaKeyTyped(evt);
            }
        });
        jPanel1.add(txtIdDetalleVenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 140, 30));

        jSeparator1.setForeground(new java.awt.Color(204, 204, 204));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 340, 140, -1));

        txtPrecio.setBackground(new java.awt.Color(34, 33, 74));
        txtPrecio.setFont(new java.awt.Font("Monospaced", 0, 16)); // NOI18N
        txtPrecio.setForeground(new java.awt.Color(204, 204, 204));
        txtPrecio.setBorder(null);
        txtPrecio.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtPrecioKeyTyped(evt);
            }
        });
        jPanel1.add(txtPrecio, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 310, 140, 30));

        jSeparator4.setForeground(new java.awt.Color(204, 204, 204));
        jPanel1.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 340, 140, -1));

        jLabel6.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(204, 204, 204));
        jLabel6.setText("Stock:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 380, -1, -1));

        btnRegistrar.setBackground(new java.awt.Color(79, 85, 137));
        btnRegistrar.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        btnRegistrar.setForeground(new java.awt.Color(204, 204, 204));
        btnRegistrar.setText("REGISTRAR");
        btnRegistrar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(169, 80, 161), 3));
        btnRegistrar.setContentAreaFilled(false);
        btnRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarActionPerformed(evt);
            }
        });
        jPanel1.add(btnRegistrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 270, 175, 40));

        btnSave.setBackground(new java.awt.Color(79, 85, 137));
        btnSave.setFont(new java.awt.Font("Monospaced", 1, 16)); // NOI18N
        btnSave.setForeground(new java.awt.Color(204, 204, 204));
        btnSave.setText("GUARDAR");
        btnSave.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(85, 197, 106), 3));
        btnSave.setContentAreaFilled(false);
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });
        jPanel1.add(btnSave, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 430, 175, 40));

        jLabel7.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(204, 204, 204));
        jLabel7.setText("Poducto:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, -1, -1));

        txtCant.setBackground(new java.awt.Color(34, 33, 74));
        txtCant.setFont(new java.awt.Font("Monospaced", 0, 16)); // NOI18N
        txtCant.setForeground(new java.awt.Color(204, 204, 204));
        txtCant.setBorder(null);
        txtCant.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCantKeyTyped(evt);
            }
        });
        jPanel1.add(txtCant, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 250, 140, 30));

        jSeparator2.setForeground(new java.awt.Color(204, 204, 204));
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 170, 140, -1));

        txtFactura.setBackground(new java.awt.Color(34, 33, 74));
        txtFactura.setFont(new java.awt.Font("Monospaced", 0, 16)); // NOI18N
        txtFactura.setForeground(new java.awt.Color(204, 204, 204));
        txtFactura.setBorder(null);
        txtFactura.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtFacturaKeyTyped(evt);
            }
        });
        jPanel1.add(txtFactura, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 140, 140, 30));

        jSeparator7.setForeground(new java.awt.Color(204, 204, 204));
        jPanel1.add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 170, 140, -1));

        txtProducto.setBackground(new java.awt.Color(34, 33, 74));
        txtProducto.setFont(new java.awt.Font("Monospaced", 0, 16)); // NOI18N
        txtProducto.setForeground(new java.awt.Color(204, 204, 204));
        txtProducto.setBorder(null);
        txtProducto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtProductoKeyTyped(evt);
            }
        });
        jPanel1.add(txtProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 200, 140, 30));

        jSeparator8.setForeground(new java.awt.Color(204, 204, 204));
        jPanel1.add(jSeparator8, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 230, 140, -1));

        jSeparator9.setForeground(new java.awt.Color(204, 204, 204));
        jPanel1.add(jSeparator9, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 280, 140, 20));

        jLabel8.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(204, 204, 204));
        jLabel8.setText("Cantidad:");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 260, -1, 20));

        jLabel9.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(204, 204, 204));
        jLabel9.setText("Factura:");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, -1, -1));

        verProducto.setBackground(new java.awt.Color(79, 85, 137));
        verProducto.setFont(new java.awt.Font("Monospaced", 0, 12)); // NOI18N
        verProducto.setForeground(new java.awt.Color(204, 204, 204));
        verProducto.setText("VER");
        verProducto.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(169, 80, 161), 3));
        verProducto.setContentAreaFilled(false);
        verProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                verProductoActionPerformed(evt);
            }
        });
        jPanel1.add(verProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 200, 50, 30));

        verFactura.setBackground(new java.awt.Color(79, 85, 137));
        verFactura.setFont(new java.awt.Font("Monospaced", 0, 12)); // NOI18N
        verFactura.setForeground(new java.awt.Color(204, 204, 204));
        verFactura.setText("VER");
        verFactura.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(169, 80, 161), 3));
        verFactura.setContentAreaFilled(false);
        verFactura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                verFacturaActionPerformed(evt);
            }
        });
        jPanel1.add(verFactura, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 140, 50, 30));

        aggProducto.setBackground(new java.awt.Color(79, 85, 137));
        aggProducto.setFont(new java.awt.Font("Monospaced", 0, 12)); // NOI18N
        aggProducto.setForeground(new java.awt.Color(204, 204, 204));
        aggProducto.setText("AGG");
        aggProducto.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(169, 80, 161), 3));
        aggProducto.setContentAreaFilled(false);
        aggProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aggProductoActionPerformed(evt);
            }
        });
        jPanel1.add(aggProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 200, 50, 30));

        aggFactura.setBackground(new java.awt.Color(79, 85, 137));
        aggFactura.setFont(new java.awt.Font("Monospaced", 0, 12)); // NOI18N
        aggFactura.setForeground(new java.awt.Color(204, 204, 204));
        aggFactura.setText("AGG");
        aggFactura.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(169, 80, 161), 3));
        aggFactura.setContentAreaFilled(false);
        aggFactura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aggFacturaActionPerformed(evt);
            }
        });
        jPanel1.add(aggFactura, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 140, 50, 30));

        txtBucarFac.setBackground(new java.awt.Color(34, 33, 74));
        txtBucarFac.setFont(new java.awt.Font("Monospaced", 0, 16)); // NOI18N
        txtBucarFac.setForeground(new java.awt.Color(204, 204, 204));
        txtBucarFac.setBorder(null);
        txtBucarFac.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtBucarFacKeyTyped(evt);
            }
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtBucarFacKeyPressed(evt);
            }
        });
        jPanel1.add(txtBucarFac, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 100, 140, 30));

        btnCancelar.setBackground(new java.awt.Color(79, 85, 137));
        btnCancelar.setFont(new java.awt.Font("Monospaced", 1, 16)); // NOI18N
        btnCancelar.setForeground(new java.awt.Color(204, 204, 204));
        btnCancelar.setText("CANCELAR");
        btnCancelar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(169, 80, 161), 3));
        btnCancelar.setContentAreaFilled(false);
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });
        jPanel1.add(btnCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 610, 175, 40));

        jSeparator6.setForeground(new java.awt.Color(204, 204, 204));
        jPanel1.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 550, 140, -1));

        txtIVA.setBackground(new java.awt.Color(34, 33, 74));
        txtIVA.setFont(new java.awt.Font("Monospaced", 0, 16)); // NOI18N
        txtIVA.setForeground(new java.awt.Color(204, 204, 204));
        txtIVA.setBorder(null);
        txtIVA.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtIVAKeyTyped(evt);
            }
        });
        jPanel1.add(txtIVA, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 520, 140, 30));

        jSeparator10.setForeground(new java.awt.Color(204, 204, 204));
        jPanel1.add(jSeparator10, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 550, 140, -1));

        jLabel12.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(204, 204, 204));
        jLabel12.setText("IVA:");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 530, -1, -1));

        txtSub.setBackground(new java.awt.Color(34, 33, 74));
        txtSub.setFont(new java.awt.Font("Monospaced", 0, 16)); // NOI18N
        txtSub.setForeground(new java.awt.Color(204, 204, 204));
        txtSub.setBorder(null);
        txtSub.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtSubKeyTyped(evt);
            }
        });
        jPanel1.add(txtSub, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 460, 140, 30));

        jSeparator12.setForeground(new java.awt.Color(204, 204, 204));
        jPanel1.add(jSeparator12, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 490, 140, 20));

        jLabel13.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(204, 204, 204));
        jLabel13.setText("SubTotal:");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 470, -1, 20));

        jSeparator13.setForeground(new java.awt.Color(204, 204, 204));
        jPanel1.add(jSeparator13, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 600, 140, -1));

        txtTotal.setEditable(false);
        txtTotal.setBackground(new java.awt.Color(34, 33, 74));
        txtTotal.setFont(new java.awt.Font("Monospaced", 0, 16)); // NOI18N
        txtTotal.setForeground(new java.awt.Color(204, 204, 204));
        txtTotal.setBorder(null);
        txtTotal.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtTotalKeyTyped(evt);
            }
        });
        jPanel1.add(txtTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 570, 140, 30));

        jSeparator14.setForeground(new java.awt.Color(204, 204, 204));
        jPanel1.add(jSeparator14, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 600, 140, -1));

        jLabel14.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(204, 204, 204));
        jLabel14.setText("Total:");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 580, -1, -1));

        txtBucarProducto.setBackground(new java.awt.Color(34, 33, 74));
        txtBucarProducto.setFont(new java.awt.Font("Monospaced", 0, 16)); // NOI18N
        txtBucarProducto.setForeground(new java.awt.Color(204, 204, 204));
        txtBucarProducto.setBorder(null);
        txtBucarProducto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtBucarProductoKeyTyped(evt);
            }
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtBucarProductoKeyPressed(evt);
            }
        });
        jPanel1.add(txtBucarProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 100, 140, 30));

        jSeparator15.setForeground(new java.awt.Color(204, 204, 204));
        jPanel1.add(jSeparator15, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 130, 140, 20));

        jLabel15.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(204, 204, 204));
        jLabel15.setText("Buscar");
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 110, -1, 20));

        txtStockActual.setBackground(new java.awt.Color(34, 33, 74));
        txtStockActual.setFont(new java.awt.Font("Monospaced", 0, 16)); // NOI18N
        txtStockActual.setForeground(new java.awt.Color(204, 204, 204));
        txtStockActual.setBorder(null);
        txtStockActual.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtStockActualKeyTyped(evt);
            }
        });
        jPanel1.add(txtStockActual, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 370, 140, 30));

        jSeparator16.setForeground(new java.awt.Color(204, 204, 204));
        jPanel1.add(jSeparator16, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 400, 140, 20));

        jLabel10.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(204, 204, 204));
        jLabel10.setText("Precio:");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 320, -1, -1));

        btnReporte.setBackground(new java.awt.Color(79, 85, 137));
        btnReporte.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        btnReporte.setForeground(new java.awt.Color(204, 204, 204));
        btnReporte.setText("FACTURA");
        btnReporte.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(169, 39, 106), 3));
        btnReporte.setContentAreaFilled(false);
        btnReporte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReporteActionPerformed(evt);
            }
        });
        jPanel1.add(btnReporte, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 620, 175, 40));

        ver.setBackground(new java.awt.Color(0, 204, 51));
        ver.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ver1.setBackground(new java.awt.Color(0, 204, 51));
        ver1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        TablaCliente1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        TablaCliente1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TablaCliente1MouseClicked(evt);
            }
        });
        jScrollPane5.setViewportView(TablaCliente1);

        ver1.add(jScrollPane5, new org.netbeans.lib.awtextra.AbsoluteConstraints(-5, -2, 380, 200));

        ver.add(ver1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 360, 380, 210));

        TablaCliente.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        TablaCliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TablaClienteMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(TablaCliente);

        ver.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 320, 130));

        jPanel1.add(ver, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 160, 380, 140));

        ver3.setBackground(new java.awt.Color(102, 0, 102));
        ver3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        TablaProducto.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        TablaProducto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TablaProductoMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(TablaProducto);

        ver3.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 310, 130));

        jPanel1.add(ver3, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 180, 320, 150));

        TablaFacturas.setBackground(new java.awt.Color(45, 55, 99));
        TablaFacturas.setForeground(new java.awt.Color(255, 255, 255));
        TablaFacturas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Factura", "Producto", "Cantidad", "Precio", "Descuento", "Monto"
            }
        ));
        TablaFacturas.setFocusable(false);
        TablaFacturas.setGridColor(new java.awt.Color(153, 153, 153));
        TablaFacturas.setIntercellSpacing(new java.awt.Dimension(0, 0));
        TablaFacturas.setRowHeight(25);
        TablaFacturas.setSelectionBackground(new java.awt.Color(47, 63, 128));
        TablaFacturas.setShowVerticalLines(false);
        TablaFacturas.getTableHeader().setReorderingAllowed(false);
        TablaFacturas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TablaFacturasMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(TablaFacturas);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 440, 270, 120));

        verr.setBackground(new java.awt.Color(79, 85, 137));
        verr.setFont(new java.awt.Font("Monospaced", 0, 12)); // NOI18N
        verr.setForeground(new java.awt.Color(204, 204, 204));
        verr.setText("VER");
        verr.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(169, 80, 161), 3));
        verr.setContentAreaFilled(false);
        verr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                verrActionPerformed(evt);
            }
        });
        jPanel1.add(verr, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 200, 50, 30));

        ver2.setBackground(new java.awt.Color(204, 204, 0));
        ver2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        TablaCliente2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        TablaCliente2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TablaCliente2MouseClicked(evt);
            }
        });
        jScrollPane6.setViewportView(TablaCliente2);

        ver2.add(jScrollPane6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 320, 140));

        ver4.setBackground(new java.awt.Color(0, 204, 51));
        ver4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        TablaCliente3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        TablaCliente3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TablaCliente3MouseClicked(evt);
            }
        });
        jScrollPane7.setViewportView(TablaCliente3);

        ver4.add(jScrollPane7, new org.netbeans.lib.awtextra.AbsoluteConstraints(-5, -2, 380, 200));

        ver2.add(ver4, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 360, 380, 210));

        jPanel1.add(ver2, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 160, 390, 180));

        TablaIngresos.setBackground(new java.awt.Color(45, 55, 99));
        TablaIngresos.setForeground(new java.awt.Color(255, 255, 255));
        TablaIngresos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        TablaIngresos.setFocusable(false);
        TablaIngresos.setGridColor(new java.awt.Color(153, 153, 153));
        TablaIngresos.setIntercellSpacing(new java.awt.Dimension(0, 0));
        TablaIngresos.setRowHeight(25);
        TablaIngresos.setSelectionBackground(new java.awt.Color(47, 63, 128));
        TablaIngresos.setShowVerticalLines(false);
        TablaIngresos.getTableHeader().setReorderingAllowed(false);
        TablaIngresos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                TablaIngresosMousePressed(evt);
            }
        });
        jScrollPane4.setViewportView(TablaIngresos);

        jPanel1.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 440, 320, 130));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 20, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txtIdDetalleVentaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtIdDetalleVentaKeyTyped

    }//GEN-LAST:event_txtIdDetalleVentaKeyTyped

    private void txtPrecioKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPrecioKeyTyped

    }//GEN-LAST:event_txtPrecioKeyTyped

    private void btnRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarActionPerformed
        if (txtFactura.getText().equals("")||txtProducto.getText().equals("")||txtCant.getText().equals("")||txtPrecio.getText().equals("")||txtStockActual.getText().equals("")) {
            javax.swing.JOptionPane.showMessageDialog(this, "No debe haber campos vacios");
        }
        else{
            TablaFacturas.setVisible(true);
            ver3.setVisible(false);
        obj[0]=txtFactura.getText();
        obj[1]=txtProducto.getText();
        obj[2]=txtCant.getText();
        obj[4]=txtStockActual.getText();
        obj[3]=txtPrecio.getText();
        
        modelo2.addRow(obj);}
        if (txtFactura.getText().equals("")||txtProducto.getText().equals("")||txtCant.getText().equals("")||txtPrecio.getText().equals("")||txtStockActual.getText().equals("")) {
            javax.swing.JOptionPane.showMessageDialog(this, "No debe haber campos vacios");
        }
        else{
        String pre;
        String can,sa,sn = null;
        double iva=0;
        double total=0;
        double subtotal=0;
        double precio;
        int cantidad,saN,sNN;
        double imp=0.0;

        for(int i=0;i<TablaFacturas.getRowCount();i++)
        {
            can=TablaFacturas.getValueAt(i, 2).toString();
            pre=TablaFacturas.getValueAt(i, 3).toString();
            precio=Double.parseDouble(pre);
            cantidad=Integer.parseInt(can);
            imp=precio*cantidad;
            subtotal=subtotal+imp;
            iva=subtotal*0.13;
            total=subtotal+iva;
            // txtcod.setText(""+Math.rint(c*100)/100)
            TablaFacturas.setValueAt(Math.rint(imp*100)/100, i, 6);
            sa=TablaFacturas.getValueAt(i, 4).toString();
            saN=Integer.parseInt(sa);
            TablaFacturas.setValueAt((saN-cantidad), i, 5);
                  
        }
        txtSub.setText(Double.toString(subtotal));
        txtIVA.setText(""+Math.rint(iva*100)/100);
        txtTotal.setText(""+Math.rint(total*100)/100);
//        txtFactura.setText("");
//        txtProducto.setText("");
//                txtStockActual.setText("");
//                txtPrecio.setText("");;
//                        txtCant.setText("");
        }
    }//GEN-LAST:event_btnRegistrarActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        
        if (txtSub.getText().equals("")||txtTotal.getText().equals("")||txtIVA.getText().equals("")) {
            javax.swing.JOptionPane.showMessageDialog(this, "No debe haber campos vacios");
        }
        else{
            
        Rfactura();
        SumarCant();
//        txtFactura.setText("");
        txtProducto.setText("");
                txtStockActual.setText("");
                txtPrecio.setText("");
                        txtCant.setText("");
                        txtTotal.setText("");
                        txtIVA.setText("");
                        txtSub.setText("");
        }
    }//GEN-LAST:event_btnSaveActionPerformed

    private void txtCantKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCantKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCantKeyTyped

    private void txtFacturaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtFacturaKeyTyped
        if (txtFactura.getText().length() >= 1) {
            evt.consume();
            Toolkit.getDefaultToolkit().beep();
        }
        //Validar que solo se puedan escribir numeros
        char validarN = evt.getKeyChar();
        if (Character.isLetter(validarN)) {
            getToolkit().beep();
            evt.consume();
            javax.swing.JOptionPane.showMessageDialog(this, "Por Favor: Ingrese solo numeros en la Factura");
        } else if ((int) evt.getKeyChar() >= 32 && (int) evt.getKeyChar() <= 47  ||
                (int) evt.getKeyChar()>=58 && (int) evt.getKeyChar()<=255){
            getToolkit().beep();
            evt.consume();
            javax.swing.JOptionPane.showMessageDialog(this, "Por Favor: Ingrese solo numeros en la Factura");
        }
    }//GEN-LAST:event_txtFacturaKeyTyped

    private void verProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_verProductoActionPerformed
        this.txtBucarProducto.setVisible(true);
        this.txtBucarFac.setVisible(false);
        String nombrecolumnas[]={"Id","Producto","Marca","Stock","Precio"};
        String data[][]=new String [0][0];
        ver.setVisible(true);
        ver2.setVisible(false);
        ver3.setVisible(false);
        TablaCliente.setModel(new DefaultTableModel(data,nombrecolumnas));
              
        
//        TablaMuestras.getTableHeader().setVisible(false);
    ListarProducto();
//        TablaMuestras.getColumnModel().getColumn(0).setMaxWidth(0);
//        TablaMuestras.getColumnModel().getColumn(0).setMinWidth(0);
//        TablaMuestras.getColumnModel().getColumn(0).setPreferredWidth(0);



       

//        TablaMuestras.getTableHeader().setVisible(false);
    }//GEN-LAST:event_verProductoActionPerformed

    private void verFacturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_verFacturaActionPerformed
        this.txtBucarProducto.setVisible(false);
        this.txtBucarFac.setVisible(true);
        String nombrecolumnas[]={"Id","Codigo","Fecha"};
        String data[][]=new String [0][0];
        TablaProducto.setModel(new DefaultTableModel(data,nombrecolumnas));
        ver.setVisible(false);
        ver2.setVisible(false);
//        TablaMuestras.getTableHeader().setVisible(false);
        ListarFactura();
    }//GEN-LAST:event_verFacturaActionPerformed

    private void aggProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aggProductoActionPerformed
//            int  fila=TablaMuestras2.getSelectedRow();
//            if (fila==-1) {
//                          javax.swing.JOptionPane.showMessageDialog(null,"Debe seleccionar una fila para agregar");
//        }else{
//                id= Integer.parseInt((String)TablaMuestras2.getValueAt(fila,0).toString());            
//                String stock=(String)TablaMuestras2.getValueAt(fila,3);
//                String pre=(String)TablaMuestras2.getValueAt(fila,4);
//                txtProducto.setText(""+id);
//                txtStockActual.setText(stock);
//                txtPrecio.setText(pre);
//                }
    }//GEN-LAST:event_aggProductoActionPerformed

    private void aggFacturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aggFacturaActionPerformed
            int  fila=TablaProducto.getSelectedRow();
            if (fila==-1) {
                          javax.swing.JOptionPane.showMessageDialog(null,"Debe seleccionar una fila para agregar");
        }else{
                id= Integer.parseInt((String)TablaProducto.getValueAt(fila,0).toString());            
                txtFactura.setText(""+id);
                }
    }//GEN-LAST:event_aggFacturaActionPerformed

    private void txtBucarFacKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBucarFacKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBucarFacKeyTyped

    private void txtBucarFacKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBucarFacKeyPressed
            String[] titulos = {"Id","Codigo","Fecha"};
        String[] registros = new String[50];

        String sql = "select id_factura_venta,codigo,fecha_venta from facturaventa WHERE fecha_venta LIKE '%" + txtBucarFac.getText() + "%'";
        modelo = new DefaultTableModel(null, titulos);
        conexion cc = new conexion();
        Connection conect = cc.connx();
        try {
            Statement st = (Statement) conect.createStatement();
            ResultSet rs = st.executeQuery(sql);
            while (rs.next()) {
                registros[0] = rs.getString("id_factura_venta");              
                registros[1] = rs.getString("fecha_venta");
                registros[2] = rs.getString("codigo");
              modelo.addRow(registros);

            }
            TablaProducto.setModel(modelo);

        } catch (SQLException ex) {
            javax.swing.JOptionPane.showMessageDialog(null, ex);
        }
    }//GEN-LAST:event_txtBucarFacKeyPressed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        
        ver3.setVisible(true);
            TablaFacturas.setVisible(false);
        cancelar();
        
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void txtIVAKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtIVAKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIVAKeyTyped

    private void txtSubKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSubKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSubKeyTyped

    private void txtTotalKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTotalKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTotalKeyTyped

    private void txtBucarProductoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBucarProductoKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBucarProductoKeyTyped

    private void txtBucarProductoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBucarProductoKeyPressed
       String[] titulos = {"Id","Producto","Marca","Stock"};
        String[] registros = new String[50];

        String sql = "select id_producto,nombre_producto,nombre_marca,stock from producto\n" +
"inner join marca on marca.id_marca=producto.id_marca WHERE nombre_producto LIKE '%" + txtBucarProducto.getText() + "%'";
        modelo = new DefaultTableModel(null, titulos);
        conexion cc = new conexion();
        Connection conect = cc.connx();
        try {
            Statement st = (Statement) conect.createStatement();
            ResultSet rs = st.executeQuery(sql);
            while (rs.next()) {
                 registros[0]=rs.getString("id_producto");
                    registros[1]=rs.getString("nombre_producto");
                    registros[2]=rs.getString("nombre_marca");
                    registros[3]=rs.getString("stock");

                modelo.addRow(registros);
            }
            TablaProducto.setModel(modelo);

        } catch (SQLException ex) {
            javax.swing.JOptionPane.showMessageDialog(null, ex);
        }
    }//GEN-LAST:event_txtBucarProductoKeyPressed

    private void txtStockActualKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtStockActualKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtStockActualKeyTyped

    private void txtProductoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtProductoKeyTyped
        if (txtProducto.getText().length() >= 1) {
            evt.consume();
            Toolkit.getDefaultToolkit().beep();
        }
        //Validar que solo se puedan escribir numeros
        char validarN = evt.getKeyChar();
        if (Character.isLetter(validarN)) {
            getToolkit().beep();
            evt.consume();
            javax.swing.JOptionPane.showMessageDialog(this, "Por Favor: Ingrese solo numeros en el Producto");
        } else if ((int) evt.getKeyChar() >= 32 && (int) evt.getKeyChar() <= 47  ||
                (int) evt.getKeyChar()>=58 && (int) evt.getKeyChar()<=255){
            getToolkit().beep();
            evt.consume();
            javax.swing.JOptionPane.showMessageDialog(this, "Por Favor: Ingrese solo numeros en el Producto");
        }
    }//GEN-LAST:event_txtProductoKeyTyped

    private void btnReporteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReporteActionPerformed
        this.factura();
    }//GEN-LAST:event_btnReporteActionPerformed

    private void TablaProductoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TablaProductoMouseClicked
//        int  fila=TablaMuestras.getSelectedRow();
//        if (fila==-1) {
//            javax.swing.JOptionPane.showMessageDialog(null,"Debe seleccionar una fila para agregar");
//        }else{
//            id= Integer.parseInt((String)TablaMuestras.getValueAt(fila,0).toString());
//            String stock=(String)TablaMuestras.getValueAt(fila,3);
//            String pre=(String)TablaMuestras.getValueAt(fila,4);
//            txtProducto.setText(""+id);
//            txtStockActual.setText(stock);
//            txtPrecio.setText(pre);
//        }
     int  fila=TablaProducto.getSelectedRow();
            if (fila==-1) {
                          javax.swing.JOptionPane.showMessageDialog(null,"Debe seleccionar una fila para agregar");
        }else{
                id= Integer.parseInt((String)TablaProducto.getValueAt(fila,0).toString());            
                txtFactura.setText(""+id);
                }
    }//GEN-LAST:event_TablaProductoMouseClicked

    private void TablaClienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TablaClienteMouseClicked
 int  fila=TablaCliente.getSelectedRow();
        if (fila==-1) {
            javax.swing.JOptionPane.showMessageDialog(null,"Debe seleccionar una fila para agregar");
        }else{
            id= Integer.parseInt((String)TablaCliente.getValueAt(fila,0).toString());
            String stock=(String)TablaCliente.getValueAt(fila,3);
            String pre=(String)TablaCliente.getValueAt(fila,4);
            txtProducto.setText(""+id);
            txtStockActual.setText(stock);
            txtPrecio.setText(pre);
        }        
    }//GEN-LAST:event_TablaClienteMouseClicked

    private void TablaCliente1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TablaCliente1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_TablaCliente1MouseClicked

    private void TablaCliente2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TablaCliente2MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_TablaCliente2MouseClicked

    private void TablaCliente3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TablaCliente3MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_TablaCliente3MouseClicked

    private void verrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_verrActionPerformed
        ver2.setVisible(true);
        ver.setVisible(false);
        ver3.setVisible(false);
    }//GEN-LAST:event_verrActionPerformed

    private void TablaFacturasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TablaFacturasMouseClicked

    }//GEN-LAST:event_TablaFacturasMouseClicked

    private void TablaIngresosMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TablaIngresosMousePressed
      
    }//GEN-LAST:event_TablaIngresosMousePressed
       public void ListarProducto(){
         String sql="select id_producto,nombre_producto,nombre_marca,stock,precio_venta from producto\n" +
                        "inner join marca on marca.id_marca=producto.id_marca";
    try{
        cn=conn.connx();
        st=cn.createStatement();
        rs=st.executeQuery(sql);
        Object[]proveedor=new Object[5];
        modelo=(DefaultTableModel)TablaCliente.getModel();
        while(rs.next()){
        proveedor[0]=rs.getInt("id_producto");
        proveedor[1]=rs.getString("nombre_producto");
        proveedor[2]=rs.getString("nombre_marca");
        proveedor[3]=rs.getString("stock");
        proveedor[4]=rs.getString("precio_venta");
        modelo.addRow(proveedor);
        
        }
        TablaCliente.setModel(modelo);
        
    }catch (Exception e){
                    javax.swing.JOptionPane.showMessageDialog(null,"Error"+e.getMessage());
        }
    }
       public void ListarFactura(){
         String sql="select id_factura_venta,codigo,fecha_venta from facturaventa where estado='activa'";
    try{
        cn=conn.connx();
        st=cn.createStatement();
        rs=st.executeQuery(sql);
        Object[]proveedor=new Object[3];
        modelo2=(DefaultTableModel)TablaProducto.getModel();
        while(rs.next()){
        proveedor[0]=rs.getInt("id_factura_venta");
        proveedor[1]=rs.getString("codigo");
        proveedor[2]=rs.getString("fecha_venta");
        modelo2.addRow(proveedor);
        
        }
        TablaProducto.setModel(modelo2);
        
    }catch (Exception e){
                    javax.swing.JOptionPane.showMessageDialog(null,"Error"+e.getMessage());
        }
       }

           public void SumarCant(){
               int fila=0;
               int total=0;
               String stockact=null;
               stockact=txtStockActual.getText();
               
               for (int i = 0; i < TablaFacturas.getRowCount(); i++) {
                   String stock=TablaFacturas.getValueAt(i, 5).toString();
                   String ide=TablaFacturas.getValueAt(i, 1).toString();
               String sql="update producto set stock='"+stock+"' where id_producto="+ide;
         if (stockact.equals("")) {
             javax.swing.JOptionPane.showMessageDialog(null, "No deben haber campos vacios");
         }else{
             try{
                 cn=conn.connx();
                 st=cn.createStatement();
                 st.executeUpdate(sql);

                 javax.swing.JOptionPane.showMessageDialog(null, "El stock ha sido actualizado");                
             }catch(Exception e){}
         }
               }
               txtStockActual.setText(""+total);
           
           }
           public void Rfactura(){
               for(int i=0;i<TablaFacturas.getRowCount();i++)
        {
            String idfac=TablaFacturas.getValueAt(i, 0).toString();
        String idprod=TablaFacturas.getValueAt(i, 1).toString();
        String cant=TablaFacturas.getValueAt(i, 2).toString();
        String preunit=TablaFacturas.getValueAt(i, 3).toString();
        String total=txtTotal.getText();
        if (total.equals("")) {
             javax.swing.JOptionPane.showMessageDialog(null,"Debe ingresar los campos que estan vacios");
         }else {
        String sql="insert into detalleventa (id_factura_venta,id_producto,cantidad,precio,total) VALUES ('"+idfac+"','"+idprod+"','"+cant+"','"+preunit+"','"+total+"')";
        
        try {          
                         cn=conn.connx();
                        st=cn.createStatement();
                        st.executeUpdate(sql);
                       
        } catch (SQLException ex) {
                        javax.swing.JOptionPane.showMessageDialog(null, "No se pudo registrar");
            }
        }
    }
        }
           
           public void factura(){
        try {
        JasperReport reporte = null;
        String path = "src/Reportes/factura.jasper";
        String idfac = txtFactura.getText();
        
        Map parametro = new HashMap();
        parametro.put("Factura", idfac);
        
            reporte = (JasperReport) JRLoader.loadObjectFromFile(path);
            JasperPrint jprint = JasperFillManager.fillReport(reporte, parametro, cn);
            JasperViewer view = new JasperViewer(jprint, false);
            view.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
            view.setVisible(true);
        } catch (JRException ex) {
            Logger.getLogger(Generar_Factura1.class.getName()).log(Level.SEVERE, null, ex);
        }
           }
           
           
     
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Generar_Factura1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Generar_Factura1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Generar_Factura1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Generar_Factura1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Generar_Factura1().setVisible(true);
            }
        });
    }
    public void cancelar(){
        txtFactura.setText("");
        txtProducto.setText("");
        txtCant.setText("");
        txtPrecio.setText("");
        txtSub.setText("");
        txtIVA.setText("");
        txtTotal.setText("");
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable TablaCliente;
    private javax.swing.JTable TablaCliente1;
    private javax.swing.JTable TablaCliente2;
    private javax.swing.JTable TablaCliente3;
    private javax.swing.JTable TablaFacturas;
    private javax.swing.JTable TablaIngresos;
    private javax.swing.JTable TablaProducto;
    private javax.swing.JButton aggFactura;
    private javax.swing.JButton aggProducto;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnRegistrar;
    private javax.swing.JButton btnReporte;
    private javax.swing.JButton btnSave;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator10;
    private javax.swing.JSeparator jSeparator12;
    private javax.swing.JSeparator jSeparator13;
    private javax.swing.JSeparator jSeparator14;
    private javax.swing.JSeparator jSeparator15;
    private javax.swing.JSeparator jSeparator16;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JSeparator jSeparator9;
    private javax.swing.JTextField txtBucarFac;
    private javax.swing.JTextField txtBucarProducto;
    private javax.swing.JTextField txtCant;
    private javax.swing.JTextField txtFactura;
    private javax.swing.JTextField txtIVA;
    private javax.swing.JTextField txtIdDetalleVenta;
    private javax.swing.JTextField txtPrecio;
    private javax.swing.JTextField txtProducto;
    private javax.swing.JTextField txtStockActual;
    private javax.swing.JTextField txtSub;
    private javax.swing.JTextField txtTotal;
    private javax.swing.JPanel ver;
    private javax.swing.JPanel ver1;
    private javax.swing.JPanel ver2;
    private javax.swing.JPanel ver3;
    private javax.swing.JPanel ver4;
    private javax.swing.JButton verFactura;
    private javax.swing.JButton verProducto;
    private javax.swing.JButton verr;
    // End of variables declaration//GEN-END:variables
}
