/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package form;

import clases.Hash;
import clases.conexion;
import java.awt.Color;
import static java.awt.SystemColor.menu;
import static java.lang.Compiler.disable;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;


public class login1 extends javax.swing.JFrame {

    static conexion cc = new conexion();
    static Connection cn = cc.connx();
DefaultComboBoxModel modelotipos;
    /**
     * Creates new form login
     */
    public login1() {
        initComponents();
        this.setLocationRelativeTo(null);
        CargarTipos();

    }
    public final void CargarTipos(){
    String [] tipo={"Administrador","Empleado"};
    modelotipos=new DefaultComboBoxModel(tipo);
    cbxTipoUsuario.setModel(modelotipos);
    }

        private void Ingresa(String usuario, String pas) {
        String user = "", pass = "";
        String cargo = "";
            
        try {
            String tuser=cbxTipoUsuario.getSelectedItem().toString();

            if (tuser.equals("Empleado")){
            
            
            String sql = "SELECT * FROM usuario WHERE nombre_usuario = '" + usuario + "'and contraseña= '" + pas + "'and id_cargo= '2'";
            Statement st = cn.createStatement();
            ResultSet rs = st.executeQuery(sql);

            while (rs.next()) {
                user = rs.getString(2);
                pass = rs.getString(4);
                cargo = rs.getString(3);
            }

            if (usuario.equals(user)) {
                if (pas.equals(pass)) {
                    if (cargo.equals("2")) {

                    }
                }
                
                this.dispose();
                
                new MenuEmp().setVisible(true);

            }  
           
            else {
                    
                    JOptionPane.showMessageDialog(null, "Ingrese un tipo de usuario correcto");
                    System.out.println("INgresaste");
                    System.out.println("Error");
                    this.txtUsuario.setText("");
                    this.txt_pass.setText("");
                    this.txtUsuario.requestFocus();
                }}
        } catch (SQLException ex) {
            Logger.getLogger(login1.class.getName()).log(Level.SEVERE, null, ex);
        }
        }
        
        
        private void Ingresa1(String usuario, String pas) {
        String user2 = "", pass2 = "";
        String cargo2 = "";

        try {

          
            
            String sql = "SELECT * FROM usuario WHERE nombre_usuario = '" + usuario + "'and contraseña= '" + pas + "'and id_cargo= '1'";
            Statement st = cn.createStatement();
            ResultSet rs = st.executeQuery(sql);

            while (rs.next()) {
                user2 = rs.getString(2);
                pass2 = rs.getString(4);
                cargo2 = rs.getString(3);
            }
            
             
                if (usuario.equals(user2)) {
                    if (pas.equals(pass2)) {
                        if (cargo2.equals("1")) {

                        }
                    }

                    this.dispose();
                    
                    new MenuAdmin().setVisible(true);

                }  
                
                else {
                    
                    JOptionPane.showMessageDialog(null, "Ingrese un nombre de usuario o contraseña validos");
                    this.txtUsuario.setText("");
                    this.txt_pass.setText("");
                    this.txtUsuario.requestFocus();
                }
                
            

            
            

        } catch (SQLException ex) {
            Logger.getLogger(login1.class.getName()).log(Level.SEVERE, null, ex);
        }

        }
   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jpingreso = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        txtUsuario = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        btnAcceder = new javax.swing.JButton();
        txt_pass = new javax.swing.JPasswordField();
        cbxTipoUsuario = new javax.swing.JComboBox<>();
        ver_pass = new javax.swing.JCheckBox();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        btnCerrar = new javax.swing.JButton();
        jButton14 = new javax.swing.JButton();

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jpingreso.setBackground(new java.awt.Color(34, 33, 74));
        jpingreso.setForeground(java.awt.Color.white);
        jpingreso.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(222, 255, 255));
        jLabel1.setText("Tipo Usuario:");
        jpingreso.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 310, 110, -1));

        jSeparator1.setBackground(new java.awt.Color(255, 255, 255));
        jpingreso.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 240, 190, 10));

        txtUsuario.setBackground(new java.awt.Color(34, 33, 74));
        txtUsuario.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        txtUsuario.setForeground(new java.awt.Color(255, 255, 255));
        txtUsuario.setBorder(null);
        txtUsuario.setCaretColor(new java.awt.Color(255, 255, 255));
        txtUsuario.setSelectedTextColor(new java.awt.Color(255, 255, 255));
        txtUsuario.setSelectionColor(new java.awt.Color(255, 255, 255));
        txtUsuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtUsuarioMouseClicked(evt);
            }
        });
        txtUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUsuarioActionPerformed(evt);
            }
        });
        txtUsuario.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtUsuarioKeyTyped(evt);
            }
        });
        jpingreso.add(txtUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 130, 190, 40));

        jSeparator2.setBackground(new java.awt.Color(255, 255, 255));
        jpingreso.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 170, 190, 10));

        btnAcceder.setBackground(new java.awt.Color(34, 33, 74));
        btnAcceder.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        btnAcceder.setForeground(new java.awt.Color(222, 255, 255));
        btnAcceder.setText("Acceder");
        btnAcceder.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(169, 80, 161)));
        btnAcceder.setContentAreaFilled(false);
        btnAcceder.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnAcceder.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                btnAccederMouseMoved(evt);
            }
        });
        btnAcceder.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnAccederMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnAccederMouseEntered(evt);
            }
        });
        btnAcceder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAccederActionPerformed(evt);
            }
        });
        jpingreso.add(btnAcceder, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 380, 175, 40));

        txt_pass.setBackground(new java.awt.Color(34, 33, 74));
        txt_pass.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        txt_pass.setForeground(new java.awt.Color(222, 255, 255));
        txt_pass.setBorder(null);
        txt_pass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_passActionPerformed(evt);
            }
        });
        jpingreso.add(txt_pass, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 210, 190, 30));

        cbxTipoUsuario.setBackground(new java.awt.Color(34, 33, 74));
        cbxTipoUsuario.setForeground(new java.awt.Color(34, 33, 74));
        cbxTipoUsuario.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(169, 80, 161)));
        cbxTipoUsuario.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jpingreso.add(cbxTipoUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 310, 190, 30));

        ver_pass.setBackground(new java.awt.Color(34, 33, 74));
        ver_pass.setForeground(new java.awt.Color(222, 255, 255));
        ver_pass.setText("Ver contraseña");
        ver_pass.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        ver_pass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ver_passActionPerformed(evt);
            }
        });
        jpingreso.add(ver_pass, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 260, -1, -1));

        jLabel3.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Usuario:");
        jpingreso.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, 80, -1));

        jLabel4.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(222, 255, 255));
        jLabel4.setText("Contraseña:");
        jpingreso.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, 110, -1));

        getContentPane().add(jpingreso, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 370, 580));

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setForeground(java.awt.Color.white);
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/divinaProvidencia.jpg"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 680, 530));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 50, 680, 530));

        jPanel3.setBackground(new java.awt.Color(34, 33, 74));
        jPanel3.setForeground(java.awt.Color.white);
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnCerrar.setBackground(new java.awt.Color(34, 33, 74));
        btnCerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/cerrar.png"))); // NOI18N
        btnCerrar.setBorder(null);
        btnCerrar.setContentAreaFilled(false);
        btnCerrar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarActionPerformed(evt);
            }
        });
        jPanel3.add(btnCerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 0, 50, 50));

        jButton14.setBackground(new java.awt.Color(45, 58, 84));
        jButton14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/minimizar.png"))); // NOI18N
        jButton14.setBorder(null);
        jButton14.setContentAreaFilled(false);
        jButton14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton14ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton14, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 0, -1, -1));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 0, 760, 50));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarActionPerformed
        int mensaje = JOptionPane.YES_NO_OPTION;
        int resultado = JOptionPane.showConfirmDialog(null,"¿Desea salir del login?","SALIR",mensaje);
        if(resultado == 0)
        {
            System.exit(WIDTH);
        }
        
    }//GEN-LAST:event_btnCerrarActionPerformed

    private void ver_passActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ver_passActionPerformed
        if (ver_pass.isSelected()) {
            txt_pass.setEchoChar((char)0);
        }else{
            txt_pass.setEchoChar('*');
        }
    }//GEN-LAST:event_ver_passActionPerformed

    private void txt_passActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_passActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_passActionPerformed

    private void btnAccederActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAccederActionPerformed
        String us = txtUsuario.getText();
        String pas = txt_pass.getText();

        if (us.equals("") || pas.equals("")) {

            this.txtUsuario.requestFocus();
            JOptionPane.showMessageDialog(null, "Ingrese nombre de usuario y contraseña");

        } else{
            String tuser=cbxTipoUsuario.getSelectedItem().toString();
            if (tuser.equals("Empleado")) {
                Ingresa(us, pas);
                ventana v = new ventana();
                v.setVisible(true);
                
            }else{
                Ingresa1(us, pas);
                ventana v = new ventana();
                v.setVisible(true);
            }

        }

    }//GEN-LAST:event_btnAccederActionPerformed

    private void txtUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUsuarioActionPerformed
        // TODO add your handling code here:
        //        jTextField4.setText(null);
    }//GEN-LAST:event_txtUsuarioActionPerformed

    private void txtUsuarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtUsuarioMouseClicked

        //    jTextField4.setText(null);
        //    if (jTextField1.getText().equals("")) {
            //            jTextField1.setText("  ingrese contraseña:");
            //        }
    }//GEN-LAST:event_txtUsuarioMouseClicked

    private void btnAccederMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAccederMouseExited
       btnAcceder.setBackground(new java.awt.Color(34,33,74));
    }//GEN-LAST:event_btnAccederMouseExited

    private void btnAccederMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAccederMouseMoved
//        btnAcceder.setBackground(new java.awt.Color(169,80,161));
    }//GEN-LAST:event_btnAccederMouseMoved

    private void btnAccederMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAccederMouseEntered
        btnAcceder.setBackground(new Color(169,80,161));
    }//GEN-LAST:event_btnAccederMouseEntered

    private void txtUsuarioKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtUsuarioKeyTyped
                //Validacion solo letras:
        //Esta funcion se encuentra en los eventos del txt en event con el nombre de KeyTyped
        char validarN = evt.getKeyChar();
        if (Character.isDigit(validarN)) {
            getToolkit().beep();
            evt.consume();
            JOptionPane.showMessageDialog(this, "Por Favor: Ingrese solo letras en el nombre");
        } else if ((int) evt.getKeyChar() >= 33 && (int) evt.getKeyChar() <= 64 ||
                (int) evt.getKeyChar()>=91 && (int) evt.getKeyChar()<=96 ||
                (int) evt.getKeyChar()>=123 && (int) evt.getKeyChar()<=208 ||
                (int) evt.getKeyChar()>=210 && (int) evt.getKeyChar()<=240 ||
                (int) evt.getKeyChar()>=242 && (int) evt.getKeyChar()<=255){
            getToolkit().beep();
            evt.consume();
            JOptionPane.showMessageDialog(this, "No se permiten caracteres especiales");
        }
    }//GEN-LAST:event_txtUsuarioKeyTyped

    private void jButton14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton14ActionPerformed
        this.setState(ICONIFIED);
    }//GEN-LAST:event_jButton14ActionPerformed
 private void limpiar() {
        txtUsuario.setText("");
        txt_pass.setText("");
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(login1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(login1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(login1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(login1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new login1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAcceder;
    private javax.swing.JButton btnCerrar;
    private javax.swing.JComboBox<String> cbxTipoUsuario;
    private javax.swing.JButton jButton14;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JPanel jpingreso;
    private javax.swing.JTextField txtUsuario;
    private javax.swing.JPasswordField txt_pass;
    private javax.swing.JCheckBox ver_pass;
    // End of variables declaration//GEN-END:variables
}
