/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package form;

import clases.Existencias;
import clases.conexion;
import static form.login1.cn;
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author cerritos
 */
public class Productos extends javax.swing.JFrame {
     conexion conn=new conexion();
    Connection cn;
    Statement st;
    ResultSet rs;
    DefaultTableModel modelo;
        DefaultTableModel modelo2;

    int id;  

    /**
     * Creates new form Productos
     */
    public Productos() {
        initComponents();
        listar();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        txtPrecioventa = new javax.swing.JTextField();
        jSeparator4 = new javax.swing.JSeparator();
        txtDescripcion = new javax.swing.JTextField();
        jSeparator5 = new javax.swing.JSeparator();
        jLabel6 = new javax.swing.JLabel();
        txtCancel = new javax.swing.JButton();
        btnEdit = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnSave = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        txtBucar = new javax.swing.JTextField();
        jSeparator7 = new javax.swing.JSeparator();
        jLabel7 = new javax.swing.JLabel();
        txtProducto = new javax.swing.JTextField();
        jSeparator8 = new javax.swing.JSeparator();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtProducto1 = new javax.swing.JTextField();
        jSeparator9 = new javax.swing.JSeparator();
        txtCategoria = new javax.swing.JTextField();
        jSeparator10 = new javax.swing.JSeparator();
        txtMarca = new javax.swing.JTextField();
        jSeparator11 = new javax.swing.JSeparator();
        txtProducto4 = new javax.swing.JTextField();
        jSeparator12 = new javax.swing.JSeparator();
        jScrollPane2 = new javax.swing.JScrollPane();
        TablaMuestras = new javax.swing.JTable();
        txtBuscarCategoria = new javax.swing.JTextField();
        jSeparator13 = new javax.swing.JSeparator();
        jLabel11 = new javax.swing.JLabel();
        txtBuscarMarca = new javax.swing.JTextField();
        txtBuscarCliente = new javax.swing.JTextField();
        verMarca = new javax.swing.JButton();
        verCategoria = new javax.swing.JButton();
        aggMarca = new javax.swing.JButton();
        aggCategoria = new javax.swing.JButton();
        txtId = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(34, 33, 74));
        jPanel1.setPreferredSize(new java.awt.Dimension(1080, 670));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(204, 204, 204));
        jLabel4.setText("Descripción:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 400, -1, -1));

        jSeparator1.setForeground(new java.awt.Color(204, 204, 204));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 360, 140, -1));

        txtPrecioventa.setBackground(new java.awt.Color(34, 33, 74));
        txtPrecioventa.setFont(new java.awt.Font("Monospaced", 0, 16)); // NOI18N
        txtPrecioventa.setForeground(new java.awt.Color(204, 204, 204));
        txtPrecioventa.setBorder(null);
        txtPrecioventa.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtPrecioventaKeyTyped(evt);
            }
        });
        jPanel1.add(txtPrecioventa, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 330, 140, 30));

        jSeparator4.setForeground(new java.awt.Color(204, 204, 204));
        jPanel1.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 360, 140, -1));

        txtDescripcion.setBackground(new java.awt.Color(34, 33, 74));
        txtDescripcion.setFont(new java.awt.Font("Monospaced", 0, 16)); // NOI18N
        txtDescripcion.setForeground(new java.awt.Color(204, 204, 204));
        txtDescripcion.setBorder(null);
        jPanel1.add(txtDescripcion, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 390, 830, 30));

        jSeparator5.setForeground(new java.awt.Color(204, 204, 204));
        jPanel1.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 420, 140, -1));

        jLabel6.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(204, 204, 204));
        jLabel6.setText("Precio venta:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 340, -1, -1));

        txtCancel.setBackground(new java.awt.Color(79, 85, 137));
        txtCancel.setFont(new java.awt.Font("Monospaced", 1, 16)); // NOI18N
        txtCancel.setForeground(new java.awt.Color(204, 204, 204));
        txtCancel.setText("CANCELAR");
        txtCancel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(169, 80, 161), 3));
        txtCancel.setContentAreaFilled(false);
        txtCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCancelActionPerformed(evt);
            }
        });
        jPanel1.add(txtCancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 290, 175, 40));

        btnEdit.setBackground(new java.awt.Color(79, 85, 137));
        btnEdit.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        btnEdit.setForeground(new java.awt.Color(204, 204, 204));
        btnEdit.setText("EDITAR");
        btnEdit.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(169, 39, 106), 3));
        btnEdit.setContentAreaFilled(false);
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });
        jPanel1.add(btnEdit, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 190, 175, 40));

        btnDelete.setBackground(new java.awt.Color(79, 85, 137));
        btnDelete.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        btnDelete.setForeground(new java.awt.Color(204, 204, 204));
        btnDelete.setText("ELIMINAR");
        btnDelete.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(85, 197, 106), 3));
        btnDelete.setContentAreaFilled(false);
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });
        jPanel1.add(btnDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 240, 175, 40));

        btnSave.setBackground(new java.awt.Color(79, 85, 137));
        btnSave.setFont(new java.awt.Font("Monospaced", 1, 16)); // NOI18N
        btnSave.setForeground(new java.awt.Color(204, 204, 204));
        btnSave.setText("GUARDAR");
        btnSave.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(169, 80, 161), 3));
        btnSave.setContentAreaFilled(false);
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });
        jPanel1.add(btnSave, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 140, 175, 40));

        jLabel1.setFont(new java.awt.Font("Monospaced", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 204, 204));
        jLabel1.setText("INGRESAR PRODUCTOS");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 40, -1, -1));

        jButton1.setBackground(new java.awt.Color(45, 58, 84));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/cerrar.png"))); // NOI18N
        jButton1.setBorder(null);
        jButton1.setContentAreaFilled(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 10, -1, -1));

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/productos.png"))); // NOI18N
        jButton2.setBorder(null);
        jButton2.setContentAreaFilled(false);
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 10, 120, 120));

        jTable1.setBackground(new java.awt.Color(45, 55, 99));
        jTable1.setForeground(new java.awt.Color(255, 255, 255));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Categoría", "Marca", "Producto", "Descripcion", "Precio venta"
            }
        ));
        jTable1.setFocusable(false);
        jTable1.setGridColor(new java.awt.Color(153, 153, 153));
        jTable1.setIntercellSpacing(new java.awt.Dimension(0, 0));
        jTable1.setRowHeight(25);
        jTable1.setSelectionBackground(new java.awt.Color(47, 63, 128));
        jTable1.setShowVerticalLines(false);
        jTable1.getTableHeader().setReorderingAllowed(false);
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 520, 980, 130));

        txtBucar.setBackground(new java.awt.Color(34, 33, 74));
        txtBucar.setFont(new java.awt.Font("Monospaced", 0, 16)); // NOI18N
        txtBucar.setForeground(new java.awt.Color(204, 204, 204));
        txtBucar.setBorder(null);
        txtBucar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtBucarKeyTyped(evt);
            }
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtBucarKeyPressed(evt);
            }
        });
        jPanel1.add(txtBucar, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 480, 140, 30));

        jSeparator7.setForeground(new java.awt.Color(204, 204, 204));
        jPanel1.add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 510, 140, 20));

        jLabel7.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(204, 204, 204));
        jLabel7.setText("Buscar");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 490, -1, 20));

        txtProducto.setBackground(new java.awt.Color(34, 33, 74));
        txtProducto.setFont(new java.awt.Font("Monospaced", 0, 16)); // NOI18N
        txtProducto.setForeground(new java.awt.Color(204, 204, 204));
        txtProducto.setBorder(null);
        txtProducto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtProductoKeyTyped(evt);
            }
        });
        jPanel1.add(txtProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 270, 140, 30));

        jSeparator8.setForeground(new java.awt.Color(204, 204, 204));
        jPanel1.add(jSeparator8, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 300, 140, 20));

        jLabel8.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(204, 204, 204));
        jLabel8.setText("Marca:");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 220, -1, 20));

        jLabel9.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(204, 204, 204));
        jLabel9.setText("Categoría:");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, -1, 20));

        jLabel10.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(204, 204, 204));
        jLabel10.setText("Producto:");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 280, -1, 20));

        txtProducto1.setBackground(new java.awt.Color(34, 33, 74));
        txtProducto1.setFont(new java.awt.Font("Monospaced", 0, 16)); // NOI18N
        txtProducto1.setForeground(new java.awt.Color(204, 204, 204));
        txtProducto1.setBorder(null);
        txtProducto1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtProducto1KeyTyped(evt);
            }
        });
        jPanel1.add(txtProducto1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 270, 140, 30));

        jSeparator9.setForeground(new java.awt.Color(204, 204, 204));
        jPanel1.add(jSeparator9, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 300, 140, 20));

        txtCategoria.setBackground(new java.awt.Color(34, 33, 74));
        txtCategoria.setFont(new java.awt.Font("Monospaced", 0, 16)); // NOI18N
        txtCategoria.setForeground(new java.awt.Color(204, 204, 204));
        txtCategoria.setBorder(null);
        txtCategoria.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCategoriaKeyTyped(evt);
            }
        });
        jPanel1.add(txtCategoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 160, 140, 30));

        jSeparator10.setForeground(new java.awt.Color(204, 204, 204));
        jPanel1.add(jSeparator10, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 190, 140, 20));

        txtMarca.setBackground(new java.awt.Color(34, 33, 74));
        txtMarca.setFont(new java.awt.Font("Monospaced", 0, 16)); // NOI18N
        txtMarca.setForeground(new java.awt.Color(204, 204, 204));
        txtMarca.setBorder(null);
        txtMarca.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtMarcaKeyTyped(evt);
            }
        });
        jPanel1.add(txtMarca, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 210, 140, 30));

        jSeparator11.setForeground(new java.awt.Color(204, 204, 204));
        jPanel1.add(jSeparator11, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 240, 140, 20));

        txtProducto4.setBackground(new java.awt.Color(34, 33, 74));
        txtProducto4.setFont(new java.awt.Font("Monospaced", 0, 16)); // NOI18N
        txtProducto4.setForeground(new java.awt.Color(204, 204, 204));
        txtProducto4.setBorder(null);
        txtProducto4.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtProducto4KeyTyped(evt);
            }
        });
        jPanel1.add(txtProducto4, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 210, 140, 30));

        jSeparator12.setForeground(new java.awt.Color(204, 204, 204));
        jPanel1.add(jSeparator12, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 240, 140, 20));

        TablaMuestras.setBackground(new java.awt.Color(45, 55, 99));
        TablaMuestras.setForeground(new java.awt.Color(255, 255, 255));
        TablaMuestras.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        TablaMuestras.setFocusable(false);
        TablaMuestras.setGridColor(new java.awt.Color(153, 153, 153));
        TablaMuestras.setIntercellSpacing(new java.awt.Dimension(0, 0));
        TablaMuestras.setRowHeight(25);
        TablaMuestras.setSelectionBackground(new java.awt.Color(47, 63, 128));
        TablaMuestras.setShowVerticalLines(false);
        TablaMuestras.getTableHeader().setReorderingAllowed(false);
        TablaMuestras.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                TablaMuestrasMousePressed(evt);
            }
        });
        jScrollPane2.setViewportView(TablaMuestras);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 170, 390, 210));

        txtBuscarCategoria.setBackground(new java.awt.Color(34, 33, 74));
        txtBuscarCategoria.setFont(new java.awt.Font("Monospaced", 0, 16)); // NOI18N
        txtBuscarCategoria.setForeground(new java.awt.Color(204, 204, 204));
        txtBuscarCategoria.setBorder(null);
        txtBuscarCategoria.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtBuscarCategoriaKeyTyped(evt);
            }
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtBuscarCategoriaKeyPressed(evt);
            }
        });
        jPanel1.add(txtBuscarCategoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 130, 140, 30));

        jSeparator13.setForeground(new java.awt.Color(204, 204, 204));
        jPanel1.add(jSeparator13, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 160, 140, 20));

        jLabel11.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(204, 204, 204));
        jLabel11.setText("Buscar");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 140, -1, 20));

        txtBuscarMarca.setBackground(new java.awt.Color(34, 33, 74));
        txtBuscarMarca.setFont(new java.awt.Font("Monospaced", 0, 16)); // NOI18N
        txtBuscarMarca.setForeground(new java.awt.Color(204, 204, 204));
        txtBuscarMarca.setBorder(null);
        txtBuscarMarca.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtBuscarMarcaKeyTyped(evt);
            }
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtBuscarMarcaKeyPressed(evt);
            }
        });
        jPanel1.add(txtBuscarMarca, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 130, 140, 30));

        txtBuscarCliente.setBackground(new java.awt.Color(34, 33, 74));
        txtBuscarCliente.setFont(new java.awt.Font("Monospaced", 0, 16)); // NOI18N
        txtBuscarCliente.setForeground(new java.awt.Color(204, 204, 204));
        txtBuscarCliente.setBorder(null);
        txtBuscarCliente.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtBuscarClienteKeyTyped(evt);
            }
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtBuscarClienteKeyPressed(evt);
            }
        });
        jPanel1.add(txtBuscarCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 130, 140, 30));

        verMarca.setBackground(new java.awt.Color(79, 85, 137));
        verMarca.setFont(new java.awt.Font("Monospaced", 0, 12)); // NOI18N
        verMarca.setForeground(new java.awt.Color(204, 204, 204));
        verMarca.setText("VER");
        verMarca.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(169, 80, 161), 3));
        verMarca.setContentAreaFilled(false);
        verMarca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                verMarcaActionPerformed(evt);
            }
        });
        jPanel1.add(verMarca, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 220, 50, 30));

        verCategoria.setBackground(new java.awt.Color(79, 85, 137));
        verCategoria.setFont(new java.awt.Font("Monospaced", 0, 12)); // NOI18N
        verCategoria.setForeground(new java.awt.Color(204, 204, 204));
        verCategoria.setText("VER");
        verCategoria.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(169, 80, 161), 3));
        verCategoria.setContentAreaFilled(false);
        verCategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                verCategoriaActionPerformed(evt);
            }
        });
        jPanel1.add(verCategoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 160, 50, 30));

        aggMarca.setBackground(new java.awt.Color(79, 85, 137));
        aggMarca.setFont(new java.awt.Font("Monospaced", 0, 12)); // NOI18N
        aggMarca.setForeground(new java.awt.Color(204, 204, 204));
        aggMarca.setText("AGG");
        aggMarca.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(169, 80, 161), 3));
        aggMarca.setContentAreaFilled(false);
        aggMarca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aggMarcaActionPerformed(evt);
            }
        });
        jPanel1.add(aggMarca, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 220, 50, 30));

        aggCategoria.setBackground(new java.awt.Color(79, 85, 137));
        aggCategoria.setFont(new java.awt.Font("Monospaced", 0, 12)); // NOI18N
        aggCategoria.setForeground(new java.awt.Color(204, 204, 204));
        aggCategoria.setText("AGG");
        aggCategoria.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(169, 80, 161), 3));
        aggCategoria.setContentAreaFilled(false);
        aggCategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aggCategoriaActionPerformed(evt);
            }
        });
        jPanel1.add(aggCategoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 160, 50, 30));

        txtId.setBackground(new java.awt.Color(34, 33, 74));
        txtId.setFont(new java.awt.Font("Monospaced", 0, 16)); // NOI18N
        txtId.setForeground(new java.awt.Color(34, 33, 74));
        txtId.setBorder(null);
        txtId.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtIdKeyTyped(evt);
            }
        });
        jPanel1.add(txtId, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 140, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1092, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    public void listarMarca(){
         String sql="select * from marca";
    try{
        cn=conn.connx();
        st=cn.createStatement();
        rs=st.executeQuery(sql);
        Object[]proveedor=new Object[2];
        modelo=(DefaultTableModel)TablaMuestras.getModel();
        while(rs.next()){
        proveedor[0]=rs.getInt("id_marca");
        proveedor[1]=rs.getString("nombre_marca");

        modelo.addRow(proveedor);
        
        }
        TablaMuestras.setModel(modelo);
        
    }catch (Exception e){
                    JOptionPane.showMessageDialog(null,"Error"+e.getMessage());
        }
    }
    
     public void listarCategoria(){
         String sql="select * from categoria";
    try{
        cn=conn.connx();
        st=cn.createStatement();
        rs=st.executeQuery(sql);
        Object[]proveedor=new Object[2];
        modelo=(DefaultTableModel)TablaMuestras.getModel();
        while(rs.next()){
        proveedor[0]=rs.getInt("id_categoria");
        proveedor[1]=rs.getString("nombre_categoria");

        modelo.addRow(proveedor);
        
        }
        TablaMuestras.setModel(modelo);
        
    }catch (Exception e){
                    JOptionPane.showMessageDialog(null,"Error"+e.getMessage());
        }
    }
     public void listar(){
         String sql="select id_producto,id_categoria,id_marca,nombre_producto,descripcion,precio_venta from producto";
    try{
        cn=conn.connx();
        st=cn.createStatement();
        rs=st.executeQuery(sql);
        Object[]proveedor=new Object[6];
        modelo2=(DefaultTableModel)jTable1.getModel();
        while(rs.next()){
        proveedor[0]=rs.getInt("id_producto");
        proveedor[1]=rs.getString("id_categoria");
        proveedor[2]=rs.getString("id_marca");
        proveedor[3]=rs.getString("nombre_producto");
        proveedor[4]=rs.getString("descripcion");
        proveedor[5]=rs.getString("precio_venta");
        modelo2.addRow(proveedor);
        
        }
        jTable1.setModel(modelo2);
        
    }catch (Exception e){
                    JOptionPane.showMessageDialog(null,"Error"+e.getMessage());
        }
    }
     public void Agregar(){
     String cat=txtCategoria.getText();
     String mar=txtMarca.getText();
     String pro=txtProducto.getText();
     String des=txtDescripcion.getText();
     String pre=txtPrecioventa.getText();
         if (cat.equals("")||mar.equals("")||pro.equals("")||des.equals("")||pre.equals("")) {
             JOptionPane.showMessageDialog(null,"Debe ingresar los campos que estan vacios");
         }else {
                String sql="insert into producto (id_categoria,id_marca,nombre_producto,descripcion,stock,precio_venta) values ('"+cat+"','"+mar+"','"+pro+"','"+des+"',0,'"+pre+"')";
                try{
                        cn=conn.connx();
                        st=cn.createStatement();
                        st.executeUpdate(sql);
                        JOptionPane.showMessageDialog(null, "El producto ha sido ingresado con exito");
                        LimpiarTable();
                }catch(Exception e){
                 //JOptionPane.showMessageDialog(null,"Error"+e.getMessage());
                }
         }
     }
     public void LimpiarTable(){
         for (int i = 0; i <= jTable1.getRowCount(); i++) {
             modelo2.removeRow(i);
             i=i-1;
         }
     }
     public void Modificar(){
         String cat=txtCategoria.getText();
     String mar=txtMarca.getText();
     String pro=txtProducto.getText();
     String des=txtDescripcion.getText();
     String pre=txtPrecioventa.getText();
         String sql="update producto set id_categoria='"+cat+"',id_marca='"+mar+"',nombre_producto='"+pro+"',descripcion='"+des+"',precio_venta='"+pre+"' where id_producto="+id;
         if (cat.equals("")||mar.equals("")||pro.equals("")||des.equals("")||pre.equals("")) {
             JOptionPane.showMessageDialog(null, "No deben haber campos vacios");
         }else{
             try{
                 cn=conn.connx();
                 st=cn.createStatement();
                 st.executeUpdate(sql);
                 JOptionPane.showMessageDialog(null, "El producto ha sido actualizado");
                 LimpiarTable();
             }catch(Exception e){}
         }
     }
     public void Eliminar(){
         int filaS=jTable1.getSelectedRow();
         if (filaS==-1) {
                 JOptionPane.showMessageDialog(null, "Debe seleccionar una fila para eliminar");
         }else{
             String sql="delete from producto where id_producto="+id;
             try{
                 cn=conn.connx();
                 st=cn.createStatement();
                 st.executeUpdate(sql);
                 JOptionPane.showMessageDialog(null, "El producto ha sido eliminado");
                 LimpiarTable();
             }catch(Exception e){}
         }
     }
     public void Cancelar(){
         this.txtCategoria.setText("");
        this.txtMarca.setText("");
        this.txtProducto.setText("");
        this.txtBucar.setText("");
        this.txtDescripcion.setText("");
        this.txtPrecioventa.setText("");
         
     }
    private void txtPrecioventaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPrecioventaKeyTyped

    }//GEN-LAST:event_txtPrecioventaKeyTyped

    private void txtCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCancelActionPerformed
            Cancelar();
    }//GEN-LAST:event_txtCancelActionPerformed

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
         String cat=txtCategoria.getText();
     String mar=txtMarca.getText();
     String pro=txtProducto.getText();
      String des=txtDescripcion.getText();
     String pre=txtPrecioventa.getText();
        if (cat.equals("")||mar.equals("")||pro.equals("")||des.equals("")||pre.equals("")) {
         JOptionPane.showMessageDialog(this, "Por Favor: Ingrese los campos");
         }
        
        Modificar();
        listar();
        this.txtCategoria.setText("");
        this.txtMarca.setText("");
        this.txtProducto.setText("");
        this.txtBucar.setText("");
        this.txtDescripcion.setText("");
        this.txtPrecioventa.setText("");
    }//GEN-LAST:event_btnEditActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
            String cat=txtCategoria.getText();
     String mar=txtMarca.getText();
     String pro=txtProducto.getText();
      String des=txtDescripcion.getText();
     String pre=txtPrecioventa.getText();
        if (cat.equals("")||mar.equals("")||pro.equals("")||des.equals("")||pre.equals("")) {
         JOptionPane.showMessageDialog(this, "Por Favor: Ingrese los campos");
         }
         else {Eliminar();
        this.txtCategoria.setText("");
        this.txtMarca.setText("");
        this.txtProducto.setText("");
        this.txtBucar.setText("");
        this.txtDescripcion.setText("");
        this.txtPrecioventa.setText("");
        listar();}
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
     String cat=txtCategoria.getText();
     String mar=txtMarca.getText();
     String pro=txtProducto.getText();
      String des=txtDescripcion.getText();
     String pre=txtPrecioventa.getText();
         if (cat.equals("")||mar.equals("")||pro.equals("")||des.equals("")||pre.equals("")) {
         JOptionPane.showMessageDialog(this, "Por Favor: Ingrese los campos");
         }
          
         else{ Agregar();
        this.txtCategoria.setText("");
        this.txtMarca.setText("");
        this.txtProducto.setText("");
        this.txtBucar.setText("");
        this.txtDescripcion.setText("");
        this.txtPrecioventa.setText("");
        listar();
         }
    }//GEN-LAST:event_btnSaveActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
             int  fila=jTable1.getSelectedRow();
            if (fila==-1) {
                          JOptionPane.showMessageDialog(null,"Debe seleccionar una fila para editar");
        }else{
                id= Integer.parseInt((String)jTable1.getValueAt(fila,0).toString());
                String cat=(String)jTable1.getValueAt(fila,1);
                String mar=(String)jTable1.getValueAt(fila,2);
                String pro=(String)jTable1.getValueAt(fila,3);
                String des=(String)jTable1.getValueAt(fila,4);
                String pre=(String)jTable1.getValueAt(fila,5);
                txtId.setText(""+id);
                txtCategoria.setText(cat);
                txtMarca.setText(mar);
                txtProducto.setText(pro);
                txtDescripcion.setText(des);
                txtPrecioventa.setText(pre);
            }
    }//GEN-LAST:event_jTable1MouseClicked

    private void txtBucarKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBucarKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBucarKeyTyped

    private void txtBucarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBucarKeyPressed

    }//GEN-LAST:event_txtBucarKeyPressed

    private void txtProductoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtProductoKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtProductoKeyTyped

    private void txtProducto1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtProducto1KeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtProducto1KeyTyped

    private void txtCategoriaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCategoriaKeyTyped
            if (txtCategoria.getText().length() >= 1) {
            evt.consume();
            Toolkit.getDefaultToolkit().beep();
        }
        //Validar que solo se puedan escribir numeros
        char validarN = evt.getKeyChar();
        if (Character.isLetter(validarN)) {
            getToolkit().beep();
            evt.consume();
            javax.swing.JOptionPane.showMessageDialog(this, "Por Favor: Ingrese solo numeros en la Categoria");
        } else if ((int) evt.getKeyChar() >= 32 && (int) evt.getKeyChar() <= 47  ||
                (int) evt.getKeyChar()>=58 && (int) evt.getKeyChar()<=255){
            getToolkit().beep();
            evt.consume();
            javax.swing.JOptionPane.showMessageDialog(this, "Por Favor: Ingrese solo numeros en la Categoria");
        }
    }//GEN-LAST:event_txtCategoriaKeyTyped

    private void txtMarcaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtMarcaKeyTyped
          if (txtMarca.getText().length() >= 1) {
            evt.consume();
            Toolkit.getDefaultToolkit().beep();
        }
        //Validar que solo se puedan escribir numeros
        char validarN = evt.getKeyChar();
        if (Character.isLetter(validarN)) {
            getToolkit().beep();
            evt.consume();
            javax.swing.JOptionPane.showMessageDialog(this, "Por Favor: Ingrese solo numeros en la Marca");
        } else if ((int) evt.getKeyChar() >= 32 && (int) evt.getKeyChar() <= 47  ||
                (int) evt.getKeyChar()>=58 && (int) evt.getKeyChar()<=255){
            getToolkit().beep();
            evt.consume();
            javax.swing.JOptionPane.showMessageDialog(this, "Por Favor: Ingrese solo numeros en la Marca");
        }
    }//GEN-LAST:event_txtMarcaKeyTyped

    private void txtProducto4KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtProducto4KeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtProducto4KeyTyped

    private void TablaMuestrasMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TablaMuestrasMousePressed

    }//GEN-LAST:event_TablaMuestrasMousePressed

    private void txtBuscarCategoriaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBuscarCategoriaKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBuscarCategoriaKeyTyped

    private void txtBuscarCategoriaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBuscarCategoriaKeyPressed
        String[] titulos = {"Id","Categoria"};
        String[] registros = new String[50];

        String sql = "select * from categoria WHERE nombre_categoria LIKE '%" + txtBuscarCategoria.getText() + "%'";
        modelo = new DefaultTableModel(null, titulos);
        conexion cc = new conexion();
        Connection conect = cc.connx();
        try {
            Statement st = (Statement) conect.createStatement();
            ResultSet rs = st.executeQuery(sql);
            while (rs.next()) {
                registros[0] = rs.getString("id_categoria");
                registros[1] = rs.getString("nombre_categoria");

                modelo.addRow(registros);

            }
            TablaMuestras.setModel(modelo);

        } catch (SQLException ex) {
            javax.swing.JOptionPane.showMessageDialog(null, ex);
        }
    }//GEN-LAST:event_txtBuscarCategoriaKeyPressed

    private void txtBuscarMarcaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBuscarMarcaKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBuscarMarcaKeyTyped

    private void txtBuscarMarcaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBuscarMarcaKeyPressed
        String[] titulos = {"Id","Marca"};
        String[] registros = new String[50];

        String sql = "select * from marca WHERE nombre_marca LIKE '%" + txtBuscarMarca.getText() + "%'";
        modelo = new DefaultTableModel(null, titulos);
        conexion cc = new conexion();
        Connection conect = cc.connx();
        try {
            Statement st = (Statement) conect.createStatement();
            ResultSet rs = st.executeQuery(sql);
            while (rs.next()) {
                registros[0] = rs.getString("id_marca");
                registros[1] = rs.getString("nombre_marca");
                modelo.addRow(registros);

            }
            TablaMuestras.setModel(modelo);

        } catch (SQLException ex) {
            javax.swing.JOptionPane.showMessageDialog(null, ex);
        }
    }//GEN-LAST:event_txtBuscarMarcaKeyPressed

    private void verMarcaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_verMarcaActionPerformed
        this.txtBuscarCategoria.setVisible(false);
        this.txtBuscarMarca.setVisible(true);
        String nombrecolumnas[]={"Id","Marca"};
        String data[][]=new String [0][0];
        TablaMuestras.setModel(new DefaultTableModel(data,nombrecolumnas));
        listarMarca();

    }//GEN-LAST:event_verMarcaActionPerformed

    private void verCategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_verCategoriaActionPerformed
        this.txtBuscarCategoria.setVisible(true);
        this.txtBuscarMarca.setVisible(false);
        String nombrecolumnas[]={"Id","Categoria"};
        String data[][]=new String [0][0];
        TablaMuestras.setModel(new DefaultTableModel(data,nombrecolumnas));
        listarCategoria();

    }//GEN-LAST:event_verCategoriaActionPerformed

    private void aggMarcaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aggMarcaActionPerformed
            int  fila=TablaMuestras.getSelectedRow();
            if (fila==-1) {
                          javax.swing.JOptionPane.showMessageDialog(null,"Debe seleccionar una fila para agregar");
        }else{
                id= Integer.parseInt((String)TablaMuestras.getValueAt(fila,0).toString());            
                txtMarca.setText(""+id);
                }
    }//GEN-LAST:event_aggMarcaActionPerformed

    private void aggCategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aggCategoriaActionPerformed
            int  fila=TablaMuestras.getSelectedRow();
            if (fila==-1) {
                          javax.swing.JOptionPane.showMessageDialog(null,"Debe seleccionar una fila para agregar");
        }else{
                id= Integer.parseInt((String)TablaMuestras.getValueAt(fila,0).toString());            
                txtCategoria.setText(""+id);
                }
    }//GEN-LAST:event_aggCategoriaActionPerformed

    private void txtBuscarClienteKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBuscarClienteKeyPressed
        String[] titulos = {"Id","Nombre","Apellido"};
        String[] registros = new String[50];

        String sql = "select id_cliente,nombre,apellido from cliente WHERE nombre LIKE '%" + txtBuscarCliente.getText() + "%'"
        + "or apellido LIKE '%" + txtBuscarCliente.getText() + "%' ";
        modelo = new DefaultTableModel(null, titulos);
        conexion cc = new conexion();
        Connection conect = cc.connx();
        try {
            Statement st = (Statement) conect.createStatement();
            ResultSet rs = st.executeQuery(sql);
            while (rs.next()) {
                registros[0] = rs.getString("id_cliente");
                registros[1] = rs.getString("nombre");
                registros[2] = rs.getString("Apellido");
                modelo.addRow(registros);

            }
            TablaMuestras.setModel(modelo);

        } catch (SQLException ex) {
            javax.swing.JOptionPane.showMessageDialog(null, ex);
        }
    }//GEN-LAST:event_txtBuscarClienteKeyPressed

    private void txtBuscarClienteKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBuscarClienteKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBuscarClienteKeyTyped

    private void txtIdKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtIdKeyTyped

    }//GEN-LAST:event_txtIdKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Productos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Productos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Productos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Productos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Productos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable TablaMuestras;
    private javax.swing.JButton aggCategoria;
    private javax.swing.JButton aggMarca;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnSave;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator10;
    private javax.swing.JSeparator jSeparator11;
    private javax.swing.JSeparator jSeparator12;
    private javax.swing.JSeparator jSeparator13;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JSeparator jSeparator9;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField txtBucar;
    private javax.swing.JTextField txtBuscarCategoria;
    private javax.swing.JTextField txtBuscarCliente;
    private javax.swing.JTextField txtBuscarMarca;
    private javax.swing.JButton txtCancel;
    private javax.swing.JTextField txtCategoria;
    private javax.swing.JTextField txtDescripcion;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtMarca;
    private javax.swing.JTextField txtPrecioventa;
    private javax.swing.JTextField txtProducto;
    private javax.swing.JTextField txtProducto1;
    private javax.swing.JTextField txtProducto4;
    private javax.swing.JButton verCategoria;
    private javax.swing.JButton verMarca;
    // End of variables declaration//GEN-END:variables
}
